### ISSUE TITLE
Bug: Lips REF #65 [Brief Description] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#100]
Is lockout of lip 'depth' for stiffening bar? 

If so, the width should be locked out, not the depth. 

There should be some way of removing that material in the event we need to. Very short planting trays are lipless and do not have a stiffening bar. 

Maybe when lip width goes to 0 there is a checkbox or something that states 'stiffening bar' that becomes checked. 

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
