### ISSUE TITLE
Bug: LargeTextSpec UI is clipped

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#1001]
Original Title: Fuse Parent UI Issue

**Bug:**
text is cut off and hard to read on fuse parent edit buttons
<img width="240" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/80caf5cc-dcde-46a2-985f-2ae005c0dbd4">

**Comment by MananPoojara** [comment]
give some padding and reduse the size of text it will work or you can give the spacing between two buttons

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.4)
