### ISSUE TITLE
Bug: SearchableSpec issue is unresolved

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1005]
Original Title: Burner price not calculating

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/ccb06dc5-ddeb-4286-bb3d-79e103ccbeba)**

**Comment by daniel11088** [comment]
doesn't show up first go around.

if I leave the build and come back it will show up

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.5)
