### ISSUE TITLE
Subtotal not updating

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1007]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/7f64c8d6-fb19-4f52-925e-3b71437b2d8b)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.5)
