### ISSUE TITLE
Bug: Resolve Fuse Triangle Issues [1.5.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#101]
To be implemented:
- Volume is calculating a rectangle, not triangle. 
- 'Enclosed' check box doesn't appear to work.
- Ability to input 3 leg lengths instead of angle

Split Pattern:
![image](https://user-images.githubusercontent.com/10405105/209190062-8502ae89-71fe-4a5a-9aaf-859b48163cc1.png)

**Comment by Reyzerbit** [comment]
Fuse triangle splitting is not planned, as would require way too many inputs to determine how split is to be made. If split alternative is proposed, perhaps split could be implemented. For now, not planned.
