### ISSUE TITLE
Bug: Routings Not Binding Properly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1017]
Original Title: Copy from 1 to 2 not transferring routings

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b1170958-8e20-4bee-b0cb-3205bfc3b2c9)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.8)
