### ISSUE TITLE
Bug: Thread Pool Overflow on large orders

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#1018]
Original Title: Loading Screen Freeze in Copy from 1.0 - 2.0

**Bug:**

Trying to duplicate Proposal 48496 from 1.0 to 2.1.7 it has been stuck on this screen for a few minutes now
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/126079d7-5792-46c7-adb4-e461981bac31)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.8)
