### ISSUE TITLE
Finish not updating

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1020]
Finish not updating in description.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/0145d9ce-0053-471c-a119-0e2ce613e327)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.8)
