### ISSUE TITLE
Auto Save data is displayed backwards

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1032]
Auto save data is showing the oldest order at the top of the list and the newest at the bottom.

Is there a way to adjust that?

I worked on 48644 and 48643 this morning and 48639 on Friday. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/4791882b-c584-4bb4-8c66-db3c42555c68)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.12](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.12)
