### ISSUE TITLE
Autosave data no longer available

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1038]
Where did the autosave data go and how do we recover it?

It disappeared after the latest update.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/8048f965-dcc4-4b71-873c-94a8f0683736)

**Comment by Reyzerbit** [comment]
Please delete your Autosaves file (C:\Users\USER\AppData\Roaming\Ore3D\Autosaves.dznts)
