### ISSUE TITLE
Bug: Fuse Details [1.5.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#104]
Fuse gusset length and angle need to automatically update per the Length, Width and Height of the fuse planter. In current state they cause an error that requires trig to solve. 

Unclear what 'gusset length' is.

Change "Fuse End Height" to "Fuse Shared Wall Height"

**Comment by Reyzerbit** [comment]
Gusset Length and Gusset Angle will be made read-only, something that is only viewable not editable, and will be calculated manually :).

Renamed Fuse End Height to "Fuse Shared Wall Height"

Gusset length is the distance from the base of the planter to where the gusset ends, but this will now be auto calculated so no longer a concern

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
