### ISSUE TITLE
Price Refresh button changes predesigns to custom

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1069]
This bug effects all standard products with children (burners, drip trays ...)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/2c37b525-9bbd-480d-8ee1-e9ec6c0bd51c)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.19](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.19)
