### ISSUE TITLE
Description [overridden] happens when an order is saved

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1070]
Why does the description get locked after a order is saved and reopened?

Is there a way to make this not happen?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/a0e12fda-6159-4ef3-aedb-75c838bedcb6)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.19](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.19)
