### ISSUE TITLE
Bug: Cost/Price of Added BOM items become zero when child is copied 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#1073]
OG
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/276b639e-bf3e-40d4-aa2f-588f9a794870)

Copy
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/cab2395b-bf35-4c1a-96b1-3eb5eab3dfc6)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.21](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.21)
