### ISSUE TITLE
Select All in 2.0 in order to revert all descriptions

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1078]
Copying from 1.0 to 2.0 over rides descriptions and currently has to reverted by individual line item.

Is it possible to select all line items and revert all descriptions at once?

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.22](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.22)
