### ISSUE TITLE
Bug: Labor and Material resetting to 1 decimal point 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#1079]
Before saving
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/f5368bbc-f5ce-491e-977f-80d2c05b89de)

After saving 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/281f9477-eaac-42b1-afdd-70607f2ec980)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.22](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.22)
