### ISSUE TITLE
Bug: Create Proposal - Space Bar Doesn't Work [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#108]
**Bug:**
Space bar isn't adding a space in any of the input fields in the 'create proposal' dialog

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
