### ISSUE TITLE
Bug: Refresh Bug (Custom Component UI)

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1085]
When adding a custom component, the component is not being added to the BOM.
In order to have the item show up, you need to refresh the price/order manually.
If the item still does not show up, you can search for it in the BOM search.

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.23](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.23)
