### ISSUE TITLE
Feature: Type to Search State

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#109]
**Feature:**
Add an option to type to search state

![image](https://user-images.githubusercontent.com/114440644/203152758-40b26650-e0f3-4677-ad46-d1f28fa243a2.png)

**Comment by Reyzerbit** [comment]
Ship Kiss Logistics is imported from NetSuite. If list is wrong, issue resides with NetSuite, not Ore3D. Talk to Mike about solution.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
