### ISSUE TITLE
Bug: Finish Pricing [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#110]
**Bug:**
Standard powder TBD is supposed to be priced at the same rate as Charcoal Gray powder.

**Comment by MattIsrael** [comment]
I don't understand this. What we pay our vendor doesn't necessarily directly inform our resale price. Our 8 standard powder coats and standard powder TBD are priced at the same rate.

**Comment by Reyzerbit** [comment]
I was under the impression that TBD intentionally had no pricing. I talked with Mike and was made aware of actual pricing to be used for TBD placeholder, reopening.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
