### ISSUE TITLE
Bug: Proposal Time Stamp in the Future

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1145]
In proposal time stamps in future. Various times into the future between different users

50111 - Gianni (mac)
50112 - Matt I (pc)
![image](https://github.com/user-attachments/assets/3e53515c-e8e5-4197-a197-4794c153aa81)

**Comment by Reyzerbit** [comment]
Completed in API: See API Update [2.2.6](https://github.com/Ore-Design/Ore3D-API/releases/tag/2.2.6)
