### ISSUE TITLE
Feature: Improve Spec Dropdown 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1146]
![image](https://github.com/user-attachments/assets/3c766a68-c499-4bf4-befd-113a40531381)

Dropdowns not always visible if too close to bottom of the screen.

**Comment by Reyzerbit** [comment]
Completed in [Release 2.4.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.4.4)

**Comment by MattIsrael** [comment]
Are we able to discuss other options to increase visibility of product names? 

@jdrake89 - As a last resort we might need to explore changing/shortening finish names (arch vs architectural), but I think we'd have to put that past Shane. I'd like to explore all other options before we even consider making our customer facing descriptions different to resolve a back-end software issue. 

![image](https://github.com/user-attachments/assets/0cfc304f-0cb0-4fe7-a40f-899739a7bf3d)


1. Search by 7 digit product # is valuable, but I don't necessarily need to see it in this drop down. If I'm searching by product # I'm going to use the full number and should only have 1 search result.
2. Can the result box scale with the number of results? 
3. Having the options appear above the input box seems like a good move. 
4. Ability to scroll horizontally is far from ideal. Having finish name still truncated with the scroll bar negates the benefit of the scroll bar.
