### ISSUE TITLE
Bug: Fuse Child Price Text in Conflict [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#115]
cost goes over " = "
![image](https://user-images.githubusercontent.com/114440644/203364410-4482a524-2437-43bf-80e6-e3404142cc45.png)

**Bug:**

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
