### ISSUE TITLE
Bug: Fuse Planter Split Mixes in Edging [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#116]
Split at default values for 230x152x22"H .25AL; 0x0 Lips

![image](https://user-images.githubusercontent.com/114440644/203365134-2eef9f38-f137-4489-a9bf-1ebaae3114db.png)

Fuse products are one or the other. Hybrid configurations will be achieved by managing shape code per child.

**Comment by Reyzerbit** [comment]
Not sure what you mean by this... feel free to talk to me or add more details to the bug report as Im not sure what youre saying here at all.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
