### ISSUE TITLE
Feature: Pinned Transactions

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1166]
Would be neat if there was a 3rd window (in addition to Autosave, Recent) on the Home screen of Ore3D where you could 'pin' a transaction that you were going to access often (ie. test proposals).

**Comment by Reyzerbit** [comment]
Completed in [Release 2.3.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.3.2)
