### ISSUE TITLE
Feature: New Fuse Children Appear with Dimensions Set to 0

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#118]
With a long list of children it would help identify new children by having their dimensions pre-set to 0, opposed to the random 32x24x24.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
