### ISSUE TITLE
Bug: Crashing when rearranging line-item

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#1181]
Ore 3D will crash when rearranging line-item
![image](https://github.com/user-attachments/assets/5768c7e7-5808-4a2a-a6a1-2c144991615b)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.3.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.3.2)

**Comment by Reyzerbit** [comment]
Completed for real in [Release 2.3.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.3.3)
