### ISSUE TITLE
Bug: Trying to exit new window is not possible

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#1199]
**Bug:**
Having an issue closing a pop out window for a proposal.

Return Home button doesn't do anything. and can't close it without force quitting Ore3D
![image](https://github.com/user-attachments/assets/ceb6ac2d-944f-46a8-b059-a7bebbea7f84)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.4.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.4.1)
