### ISSUE TITLE
Feature: Adjust Title So Entire Transaction # is Listed

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1211]
Regardless of screen size the full transaction # should always be visible.

![image](https://github.com/user-attachments/assets/f75634d7-c336-44a8-8e2e-f1f9e5cf8138)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.4.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.4.4)
