### ISSUE TITLE
Bug: Font Size and Margins (UI)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1228]
Proposal sub-total not visible. 
![image](https://github.com/user-attachments/assets/5fd99ebc-7971-49fa-9779-61e2d3e448bf)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.5.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.5.0)
