### ISSUE TITLE
Bug: BOM item price being removed from subtotal when ignore parent qty checkbox is checked. 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#1230]
![image (3)](https://github.com/user-attachments/assets/4f3bb221-b269-4196-ba55-44d757a24281)
![image (2)](https://github.com/user-attachments/assets/7a8c017a-9d14-41d0-a5c3-d16cac005a55)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.5.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases)
