### ISSUE TITLE
Bug: Hide non-selectable additional routings.

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1240]
![image](https://github.com/user-attachments/assets/e4ed2d1b-0dfc-4f4c-b3a1-f175b5b21426)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.5.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.5.3)
