### ISSUE TITLE
Bug: Display description checkbox  reverting after save

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#1243]
Abstract (not sure if other shape codes are affected)

Affected Items: Normal BOM Items:

Behavior:
Uncheck 'display in description'. This works
Save proposal
re-open proposal
****
At this point the description is overridden and the 'display in description' check box is RE-checked.

**Comment by Reyzerbit** [comment]
Completed in [Release 2.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.5.4)
