### ISSUE TITLE
Feature: Price Override

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#125]
We need to be able to override the following prices within Ore3D

Final Price
Material Price
Option Price

**Comment by Reyzerbit** [comment]
Unsure what "Material Price" and "Option Price" is referring to exactly. Can you please elaborate?

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
