### ISSUE TITLE
Bug: Finish Availability [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#126]
Powder Coats should not be available under the Finish Type: Patina.

![image](https://user-images.githubusercontent.com/114440644/203590118-d0317c24-f028-4573-9281-c436f0c2f9ac.png)

**Comment by Reyzerbit** [comment]
Finish type is not selectable and is auto set based on which finish is currently selected. Possible solution will be to remove finish type spec from being displayed to avoid this confusion.

**Comment by MattIsrael** [comment]
I don't understand. I thought finish type filtered the specific finish options?

**Comment by Reyzerbit** [comment]
It does not. Finish type is simply a display for the type of finish associated with the one selected. Try selecting different finishes and you will see that field change.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
