### ISSUE TITLE
Feature: Description Changes

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#129]
### Solution
We need to be able to view the the complete description that will go to NetSuite and also have the ability to edit that description.

### Disclaimers
1-Automated disclaimers (only 1 instance of the disclaimer/proposal. Always at the bottom.):
examples:
-Natural Rust = Rust Disclaimer
-Oxidized Zinc = Ox. Zinc Disclaimer
-Custom= Shop Drawings Disclaimer

2-Ability to add Proposal Note - essentially this is a line item with no cost where we can type any notes that wouldn't live within a specific line item. Typically applying to the entire proposal.

### Fuse Description Recommended Format
[Label]
[L" (LF if edging)] x [width"] x [height"]H [product*] [[material gauge"]]; [Finish Type]: [Specific Finish]
[Custom Description]

Perimeter Edging
794LF x 14"W x 33"H Unanchored Aluminum Linear FuSE Retention Edging [.25", ]; Powder Coat Finish: TBD

Product* (maybe shape code in Ore3D?)
-Linear Fuse Planter
-Curved Fuse Planter
-Linear Fuse Retention Edging - Anchored/Un-Anchored
-Curved Fuse Retention Edging - Anchored/Un-Anchored

### Non Fuse Description Recommended Format

[Label]
[L"] x [width"] x [height"]H [product*] [[material gauge"]]; [Finish Type]: [Specific Finish]
[Custom Description]

Product* (examples)
-Modified Rectangle
-Modified Column Water Feature
-Modified Linear Fire Feature

**Comment by MattIsrael** [comment]
This feature is of critical importance. Estimating is responsible for generating a price which is qualified by the description which appears in NetSuite. It is common for us to need to manipulate this description to properly describe what we are pricing.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
