### ISSUE TITLE
Bug: Pressing Tab Causes Crash [1.4.4]

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#13]
**Bug:**
Pressing tab key in edit menu causes crash.

NullReferenceException: Object reference not set to an instance of an object

TabControl.Update () (at <20166bb1668c4e2b83ca89a608e1a1b2>:0)

—————————————————————————

**Comment by Reyzerbit** [comment]
Fixed with [Update v1.4.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.4.5)
