### ISSUE TITLE
Feature: Custom Fire Pit Calculator

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#130]
See attached PDF.

Contact MI with questions. 
[Custom Fire Pits.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10108097/Custom.Fire.Pits.pdf)

Allow for a Fuse option. Would impact body, pan and lid.

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
