### ISSUE TITLE
Bug: Add Tag [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#131]
Can't back out of 'Add Organizational Tag' if you go in there by accident, without adding a tag. 

Escape or cancel...

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
