### ISSUE TITLE
Bug: Parent Fuse Values - Rounding [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#132]
round up to closest integer. Decimals are not needed here. 

![image](https://user-images.githubusercontent.com/114440644/204586221-14fa63b7-0e8d-42ee-84cd-39f247044723.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.5)
