### ISSUE TITLE
Feature: Fuse Qty Process

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#136]
I believe this proposed process would be benefit everyone (estimating, PMs, Ore). It would also resolve an existing business process defect.

Add to Fuse Parent:
- Parent Qty: this will represent a qty associated with the entire assembly
- Fuse Section Override (PM use): At time of PM reconciliation the PM will be able to override the section qty. 
 
This would divide the total parent Routings and BOM to match the Ore shop drawings thus creating the correct # of WOs. This would require a 3rd NetSuite qty column. (parent qty, WO qty, Estimated qty). 

[Fuse Parent Section Qty Override.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10117808/Fuse.Parent.Section.Qty.Override.pdf)

Improvements Over Current Process:
- Preserves 'as estimated' data allowing for first ever feedback loop to estimating.
- Preserves full routings and BOM that were sold/estimated - Currently PM reconciliation adjusts times/BOM away from 'as sold'
- EASY for PMs - Faster and more accurate than current process

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
