### ISSUE TITLE
Other: Remove planted weight from fire pits

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#139]
Remove planted weight from fire pits

![image](https://user-images.githubusercontent.com/114440644/206311953-d99d6669-ed5b-41f9-b7d4-29cd585d68d4.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
