### ISSUE TITLE
Bug: Crash on Clicking Search in Project Search [1.4.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#14]
**Bug:**
I was experiencing very poor performance. I tried to save my estimate. Upon doing this it asked me to find a project (?). i typed "test" into the search bar then the app crashed.

**Recreate:**
1. Load expired proposal with no selected project.
2. Attempt to save proposal.
3. When prompted to select project, click "Search" button.
4. See crash.

**Expected Behavior:**
No crash should occur.

**Additional Context/Questions:**

ArgumentNullException: Value cannot be null.
Parameter name: target

UnityEngine.Events.BaseInvokableCall..ctor (System.Object target, System.Reflection.MethodInfo function) (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.InvokableCall..ctor (System.Object target, System.Reflection.MethodInfo theFunction) (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.PersistentCall.GetRuntimeCall (UnityEngine.Events.UnityEventBase theEvent) (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.PersistentCallGroup.Initialize (UnityEngine.Events.InvokableCallList invokableList, UnityEngine.Events.UnityEventBase unityEventBase) (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.UnityEventBase.RebuildPersistentCallsIfNeeded () (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.UnityEventBase.PrepareInvoke () (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.UI.Button.Press () (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.EventSystems.EventSystem:Update()

—————————————————————————

**Comment by Reyzerbit** [comment]
Fixed with [Update v1.4.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.4.5)
