### ISSUE TITLE
Other: Move 'Cubic Feet' to Overview

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#140]
Please remove 'cubic feet' from fire pits. 

Move on planters:
![image](https://user-images.githubusercontent.com/114440644/206312184-ecdd9498-05af-427d-a684-e0ed16662a83.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
