### ISSUE TITLE
Bug: Lips [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#141]
Lip Width - used to be a drop down, but now can enter any value. I'm ok with this, just wanted to check it was intentional

Lip Depth - should be a 'driven' field to match the Lip Width. - Can be overridden to a value =or <Lip Width
(If the height is > width the material hits the brake press) - we could account for this with different fab rates, but I don't want to do that now.

**Comment by Reyzerbit** [comment]
I have no recollection of Lip Width being a dropdown. Pretty sure it's always been free entry.

Lip Depth: Planned to be fixed with #102
