### ISSUE TITLE
Other: Finish Selection - Display

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#142]
After finish is selected it should show:
Option 1: red circled text
Option 2: green circled text

![image](https://user-images.githubusercontent.com/114440644/206313280-bc344ce0-3e59-419f-a3bd-2415f871689b.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
