### ISSUE TITLE
Feature: Fuse Split Section Table

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#145]
Add 2 things:
- Table showing default section qty then section qty +/- 5. As seen in the snippet below. 
- Add field where we can adjust the default value of +/- 5. When we have super long fuse edging runs each section break could result in only an inch or 2 of section length difference, in which case we'd want to increase the table to show more results. 

![image](https://user-images.githubusercontent.com/114440644/206763108-c32d0e00-a798-40cc-99d5-556a6fb6bc3d.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
