### ISSUE TITLE
Bug: Standard Item BOM Conflicts/Errors [1.5.5]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#146]
### Predesigned items need to be reviewed for BOM & Detail accuracy

-Material Gauge
-Lip Width

### Water Feature Missing Components

![image](https://user-images.githubusercontent.com/114440644/206798097-d0949f63-e42f-46fe-805d-85088624556c.png)

### Predesigned Price Override

Is this how standard items have their pricing 'overriden'?

If so, option pricing needs to flow through. Additionally, it would be helpful for these prices to match. 

![image](https://user-images.githubusercontent.com/114440644/206797185-28e0c775-8450-4508-b5af-25b9f9cd1be2.png)

### Add Shape Inconsistencies
Column is the only water feature that has a 'custom' button

![image](https://user-images.githubusercontent.com/114440644/206798403-cf0a19ff-34cd-4d2a-9380-1703cfa5ad32.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
