### ISSUE TITLE
Bug: Total Price per Unit Not Updating Line item Cost [1.5.5]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#147]
Is this how standard items have their pricing 'overriden'?

If so, option pricing needs to flow through. Additionally, it would be helpful for these prices to match. 

![image](https://user-images.githubusercontent.com/114440644/206797185-28e0c775-8450-4508-b5af-25b9f9cd1be2.png)

**Comment by Reyzerbit** [comment]
Merging with #146
