### ISSUE TITLE
Bug: [Create Proposal Button Doesn't Work] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#15]
**Bug:**
In sandbox: Create Proposal Button Doesn't Work from main landing page.

**Comment by Reyzerbit** [comment]
Fixed with [Update v1.4.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.4.6)
