### ISSUE TITLE
Feature: Finish Selection Presentation

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#150]
Please present selected finish as display name [part#].
Ex. Charcoal Gray (135-1010)

Ensure the entire text is visible somehow. May be challenging on longer finish labels

![image](https://user-images.githubusercontent.com/114440644/206798884-82bc58b5-a43b-4964-8b7f-44896e65c29c.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
