### ISSUE TITLE
Bug: Receipts Option Price Formatting [1.5.5]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#152]
Minor formatting error on receipts 

![image](https://user-images.githubusercontent.com/114440644/206799655-1baaa422-86f2-4eb9-9f4d-2df6183f5fc9.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)

**Comment by MattIsrael** [comment]
Issue is persistent

![image](https://user-images.githubusercontent.com/114440644/208199834-0d5fe86b-8461-49cf-8f36-29b4a2e8da12.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.0)
