### ISSUE TITLE
Bug: Missing Fire Pit Options [1.5.5]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#153]
PDF with recommended changes to Fire Pit Calculator system:
[Fire Pit Details.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10232298/Fire.Pit.Details.pdf)

Additionally, the following options are not available in the calculator:
-Granite
-Raised AL Top
-Glass Surround
-Lid

**Comment by Reyzerbit** [comment]
Being replaced in 1.7.1 with new child-structure system.
