### ISSUE TITLE
Feature: Fire Pit Details

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#160]
**Issue:**

**Solution:**

**Alternatives:**

**Additional Context/Questions:**
[Fire Pit Details.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10232298/Fire.Pit.Details.pdf)

**Comment by Reyzerbit** [comment]
Merging with Bug Report #153
