### ISSUE TITLE
Bug: Cylindrical products have nearly doubled SF [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#162]
~~#146~~
~~BOM not resolved~~

~~Example A1217~~
~~Material SF incorrect~~
~~Times incorrect (aren't the times supposed to match experlogix on the standards?)~~

Calculation for cylindrical products appears to be incorrect, resulting in SF inaccuracies.

**Comment by Reyzerbit** [comment]
Times are not meant to match Experlogix, they use new calculation data to reflect more accurate times based on updated data.
Turns out SF issue was related to code error not database inaccuracies, changing bug to report that issue.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.0)
