### ISSUE TITLE
Bug: Capsule/You Products using Incorrect BOM Components [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#163]
Example: 
Anything with Bowl
ex. 
A1206 - too much sheet material, no bowl
S1206 - too much sheet material, no bowl
A1235 - too much sheet material, no bowl
A1237 - too much sheet material, no bowl
A1209 - too much sheet material, no bowl

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.0)
