### ISSUE TITLE
Bug: Material Selection Doesn't Filter Thickness Options [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#167]
Material + Thickness drop downs:

- Doesn't filter available materials
- 14 & 11 gauge don't add material line to BOM
- Allows for selection of .090" steel which doesn't exist. Steel analog to .090" (aluminum) is 14 gauge or .074" as a decimal

Mild Steel - .090" maps to 102-2008 which is 14ga. steel
- The NetSuite description is correct. .090" steel doesn't exist

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.0)
