### ISSUE TITLE
Bug: Band Planter [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#169]
ex. A1116
- No sure how it's calculating material (doesn't match standard BOM or estimations)
- Wood not in BOM
- Incorrectly lists a skirt
- There is a standard price override, but I don't know what it's drawing from. We don't have a set price for this in our catalog.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.5)
