### ISSUE TITLE
Bug: [Bowl Fire Pit - Crash] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#17]
**Bug:**
Create from shape>Fire Pit> Fire Bowl>Add to order-CRASH

**Additional Context/Questions:**
InvalidOperationException: Nullable object must have a value.

System.Nullable`1[T].get_Value () (at <695d1cc93cca45069c528c15c9fdd749>:0)
ModelPanel.UpdateVisuals (System.Collections.Generic.List`1[T] selectedBuilds) (at <d67c1115e008461a84240e94b4921ea4>:0)
BuildTileList.SendSelectionChangeEvent () (at <d67c1115e008461a84240e94b4921ea4>:0)
BuildTileList.SelectTile (BuildTile tile, System.Boolean sendChangeEvent) (at <d67c1115e008461a84240e94b4921ea4>:0)
BuildTileList.CreateNewBuildTile (Build newBuild) (at <d67c1115e008461a84240e94b4921ea4>:0)
NewBuildPanel.HandleSubmit () (at <d67c1115e008461a84240e94b4921ea4>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <78bbea09abae4fde839ce4ad41cda53f>:0)
UnityEngine.UI.Button.Press () (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <47959a69b56c459aa6f04d3eb41cc659>:0)
UnityEngine.EventSystems.EventSystem:Update()

—————————————————————————

**Comment by Reyzerbit** [comment]
Fixed with [Update v1.4.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.4.6)

**Comment by Reyzerbit** [comment]
Fixed with [Update v1.4.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.4.6)
