### ISSUE TITLE
Bug: Burner Price, Part# and Description [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#175]
See corresponding email with attachment. 

•	Please provide Ore3D override pricing based on the NetSuite Part# & Pricing sheet (current burner pricing is incorrect)
•	Verify all current part #s are active. (351-1010 is inactive, but still pulls up as the default option for the 4020)
•	Adjust Ore3D so the ‘display text’ for burners matches Experlogix. Jake Drake have this text in NetSuite already. Should be in the **Text for Custom Description** field, but please verify that it matches Experlogix and the naming format below.

Description (internal):
[HPC part#] – [Ore Fire Pit Model #]
            Examples:
•	121X8SSEI-L-NG/120VAC
•	37X8SSEI-L-NG/120VAC – 4020
•	This would allow the user to still filter by standard fire pit model to narrow their search
 
Text for Custom Description:
[dims] [fuel] [ignition], [current(if EI)] [[HPC Part#]]
 
Examples:
•	121 X 8 Natural Gas, Electronic Ignition, 120VAC [121X8SSEI-L-NG/120VAC]

**Comment by Reyzerbit** [comment]
Merging with #165
