### ISSUE TITLE
Feature: Fire Feature Details Pop-Out for Pre-Designed

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#176]
Have the Fire Feature Details pop-out work for pre-designed(catalog) and automatically filter options to ONLY show options that match that fire feature. 

*If someone wants to make the fire feature custom they will need to do that outside of the pop-up.

**Comment by Reyzerbit** [comment]
Being replaced in 1.7.1 with new child-structure system.
