### ISSUE TITLE
Feature: Labels and Pre-Designed Item Descriptions

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#177]
- Label default to blank (can't be used for internal descriptions) 
- Pre-Designed elements need part # + [product shape code] ex. Cylinder, High Rectangle, Column Water Feature. 

[Item Descriptions.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10309748/Item.Descriptions.pdf)

**Comment by Reyzerbit** [comment]
Merging with #165
