### ISSUE TITLE
Bug: Standard Option Prices Not in Ore3D [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#178]
### Original Request
Prices for our catalog options are not pulling into Ore3D. 

Pulling info out of experlogix is likely the easiest. 
Examples: 
-Drainage Fittings
-Irrigation Sleeves
-Removable Toe Kicks

### Finishes
The prices that Ore3D is drawing from NetSuite don't reflect the 'advertised' price for specific finishes.

We have 2 price points for powder coats Standard and Architectural. The custom finishes are just whatever their actual cost is, but these 2 have set prices/LB that need to override the actual purchase price.

There is no pricing for Natural Rust Patina or Oxidized Zinc.

### Fire Pits
Fire Features Options not available:

- Lids
- Glass Surround
- Raised Top (if available)
- Other

### Burners
See corresponding attachment for following points:
[Standard Burner Matrix.xlsx](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10313018/Standard.Burner.Matrix.xlsx)
- Please provide Ore3D override pricing based on the NetSuite Part# & Pricing sheet (current burner pricing is incorrect)
- Verify all current part #s are active. (351-1010 is inactive, but still pulls up as the default option for the 4020)

**Comment by Reyzerbit** [comment]
Being handled by Matt Israel and the operations dept.
