### ISSUE TITLE
Bug: [Add standard Askew - CRASH] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#18]
**Bug:**
Add standard Askew - CRASH

**Additional Context/Questions:**
(Sorry I can't 're-copy the error code) same as previous bugs

**Comment by Reyzerbit** [comment]
Fixed with [Update v1.4.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.4.6)
