### ISSUE TITLE
Feature: Add Build - Enhancements

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#181]
- Default to General Products (showing Planter, Water Feature, Fire Feature...)
- Add dimensions below product #
- Group Base planters into single category
- Group Rectangles into single category
- Group Columns into single category
- Group Corners into single catagory
- When Shape Code is selected show materials across the top (Aluminum, Mild Steel, Corten) - this will filter individual planter options
- Organize individual planter(s) into Columns of part# descending - See image
[Add Build- General.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10310064/Add.Build-.General.pdf)

**Comment by Reyzerbit** [comment]
Merging with #165
