### ISSUE TITLE
Bug: Standard Options for Pre-Designed Fire Features Not Available [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#182]
Fire Features Options not available:

- Lids
- Glass Surround
- Raised Top (if available)
- Other

**Comment by Reyzerbit** [comment]
Does this mean they aren't available in Ore3D at all? Or just the pricing?

Almost all of these should be available via the "Add BOM Component" button in the receipts panel, but I'm not sure if the pricing is there quite yet

**Comment by MattIsrael** [comment]
I am not able to find the items. I tried searching for '4020' and 'lid' looking for the 4020 lid and found nothing.

**Comment by Reyzerbit** [comment]
Okay I probably missed some, thanks you. Merging with #178
