### ISSUE TITLE
Bug:  Changes Require Click Out/In to Item [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#184]
Some selections require clicking out of, and back into item for it to take effect (ex. Oxidized Zinc Patina). These changes need to be recognized immediately. 

Exists in Fuse Splitter too. More difficult to deal with here

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.0)
