### ISSUE TITLE
Feature: Fuse Product Selection [1.5.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#185]
Select fuse product type (edging, planter, etc) in a similar way to a planter shape code - before you get into the configurator

Currently you have to add a child and remove the default child simply to select a shape code.

**Comment by Reyzerbit** [comment]
Being implemented in 1.7.1 by simply adding fuse as empty every time.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.1)
