### ISSUE TITLE
Bug: Finish Prcing[Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#186]
Finishes require price match to match catalog.

**Comment by Reyzerbit** [comment]
Please provide more detail as I'm not sure what this means

**Comment by MattIsrael** [comment]
The prices that Ore3D is drawing from NetSuite don't reflect the 'advertised' price for specific finishes. 

We have 2 price points for powder coats Standard and Architectural. The custom finishes are just whatever their actual cost is, but these 2 have set prices/LB that need to override the actual purchase price.

**Comment by Reyzerbit** [comment]
Merging with #178
