### ISSUE TITLE
Feature: [Copy Bug Text More Than 1x]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#19]
**Issue:**
Copy Error code text only allows text to be copied one time. Can not highlight text to copy in that way.

**Solution:**
allow text to be copied infinite times. 

**Alternatives:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
No plan to implement: crash error messages will soon be automated and automatically sent to me, so this feature would be removed soon after being added.
