### ISSUE TITLE
Bug: Crash when Child is Added while Parent Tile is Selected [1.6.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#197]
Add Fuse>Delete Placeholder Child>Add child (allows you to actually select the shape code)>CRASH

**Comment by Reyzerbit** [comment]
Implemented/fixed in [Version 1.6.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.2)
