### ISSUE TITLE
Bug: Fuse Details RESET After Split [1.6.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#198]
### Lips
Fuse child entered at total dims (pre-split). Lips set to 2x2
after split lips reset to 1x1

### Height/Width
Edging Width CHANGES TO 1/2 OF HEIGHT
After Split section length and width are not provided. There is a "-" through the fields so it's not easily reviewed

### Thickness
Thickness Data isn't carried over.

**Comment by Reyzerbit** [comment]
Implemented/fixed in [Version 1.6.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.2)

**Comment by Reyzerbit** [comment]
Issue has apparently resurfaced in 1.6.4 for thickness specifically.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.0)
