### ISSUE TITLE
Bug: Split Fuse Button not Reappearing After Split [1.6.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#200]
Issue has temporary fix of clicking fuse tile again, but preferred outcome would be the button to just not disappear.

**Comment by Reyzerbit** [comment]
This appears to be resolved with the new codebase rewrite. ( See #228 ) If issue persists after version 1.7.0, please submit a comment to reopen bug.
