### ISSUE TITLE
Bug: Fuse Edging Fab Time  and Material SF Seems Really Low [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#202]
Fuse Edging fab time is a little more than 50% of the fab time calculated in Experlogix. This leads to notably lower product costs.

Edging SF notably lower than experlogix - is it adding gussets and yield? 

Do we have data showing this is acceptable? Can we pull edging fab times to review?

**Comment by Reyzerbit** [comment]
Fuse Edging pricing has been updated to more closely reflect Experlogix values. Please update your database to see change.

**Comment by MattIsrael** [comment]
@Reyzerbit would you please reopen this bug. I am not showing it has been resolved.

Additionally, there is not extra fab time being added for 'curved' elements.
