### ISSUE TITLE
Bug: Ore3D Prices Rounding! NetSuite Price Doesn't Match Ore3D [1.6.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#204]
REF: 40962

Product prices in Ore3D do not match NetSuite outputs!

**Comment by Reyzerbit** [comment]
Implemented/fixed in [Version 1.6.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.2)
