### ISSUE TITLE
Feature: Allow Fuse Shape Code Change After Creation

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#206]
Allow for Fuse shape code to be changed after initial creation.

I see this preventing a lot of rework and additionally helping making pricing comparisons more efficient. 

This would be used very often. Valuable feature in experlogix.

**Comment by Reyzerbit** [comment]
Setting as low priority. This would require massive backend code changes. Planned for distant future.

**Comment by Reyzerbit** [comment]
Deemed unnecessary after coding time-to-benefit ratio.
