### ISSUE TITLE
Bug: [Skid Crashes Program] [1.6.2]

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#217]
**Bug:**
I selected a skid and the program crashes

**Recreate:**
1. Load order 
2.  Choose dimensions of planter
3. select a skid
4. crash

**Expected Behavior:**
We should be able to have a skid

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.3)
