### ISSUE TITLE
Bug: 4020 Firepit Sizing Wrong [1.6.2]

### ISSUE THREAD

**Issue by cwatson-ore** [Ore-Design/Ore-3D-Reports-Changelog#218]
**Bug:**
4020 fireplace size in ORE3D - 67" x 32" x 14". 4020 fireplace size in catalog - 67" x 34" x 14"

**Expected Behavior:**
Needs change to standard size in all finishes

**Additional Context/Questions:**
![Screen Shot 2023-01-04 at 1 14 45 PM](https://user-images.githubusercontent.com/121980302/210651832-8b3b2467-a3f8-48d2-8291-da2260824afe.png)
![Screen Shot 2023-01-04 at 1 15 02 PM](https://user-images.githubusercontent.com/121980302/210651851-ed5e4bc7-f3ba-4709-bde3-723a9c9aecfc.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.3)
