### ISSUE TITLE
Bug: 4020 Firepit standard options not available - Ore3D Version 1.6.1

### ISSUE THREAD

**Issue by cwatson-ore** [Ore-Design/Ore-3D-Reports-Changelog#219]
**Bug:**
Standard options not available for 4020 Firepit. 

**Expected Behavior:**
Should be able to add lid, glass surround, media, etc. 

**Additional Context/Questions:**
![Screen Shot 2023-01-04 at 1 31 38 PM](https://user-images.githubusercontent.com/121980302/210652300-28243561-e099-47ac-89c2-3780495b7313.png)

**Comment by Reyzerbit** [comment]
Said components are available but may not have pricing. I'll show you where.
