### ISSUE TITLE
Feature: Bison Description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#220]
![image](https://user-images.githubusercontent.com/114440644/210887964-bff1df1c-8258-4e8b-b151-30ab78f7bc1a.png)

Continuity in description. Add width to 24", 72" and 96"

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.6.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.6.4)
