### ISSUE TITLE
Bug: Clicking Red Conflicts Indicator Freezes Application [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#226]
Ore3D became unresponsive when I clicked the red error. Unable to proceed. 

![image](https://user-images.githubusercontent.com/114440644/211357429-41bf0963-428f-49ac-959b-9af3c59b9b09.png)

**Comment by Reyzerbit** [comment]
Issue resides with poor performance. New performance rewrite should resolve this issue. Closing and merging with #228
