### ISSUE TITLE
ENHANCE PERFORMANCE CODE OVERHAUL

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#228]
RE: 40962

Ore3D is very laggy requiring multiple clicks to select a different build.

Note from JRB: Massive code overhaul is planned for Ore3D performance improvement. Once this overhaul begins, additional bugs and feature additions will be halted for the better part of a week. Therefore, this project will begin as soon as IT department and Estimation/Sales department come to an agreement on a good pause point for bug fixes/feature requests.

Notes for overhaul project:
- Switch from event system to "flag as needing recalculating"
- Create GUI update order
- Implement menu component interface for calling GUI updates.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.0)
