### ISSUE TITLE
Bug: CAD Qty Discount [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#231]
All NON-Fuse, custom items that have a quantity discount that only applies to the CAD time/costs.

[CAD Time]/Line qty=Unit CAD time

Regardless of the quantity we only charge CAD time for 1 unit per line.

**Comment by Reyzerbit** [comment]
This is because CAD only has to be done once per shape. You don't redraw the product per quantity, you draw it once and use the same drawing for all work orders.
