### ISSUE TITLE
Bug: Save Pop-up [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#234]
sometimes the save icon is grayed out, but the back icon still gives you the 'are you sure' popup error.

![image](https://user-images.githubusercontent.com/114440644/211420705-ed4f7bc6-aa45-41d1-acce-1b227b03aa04.png)

**Comment by Reyzerbit** [comment]
Unable to replicate, possibly fixed with new codebase rewrite ( see #228 ). If issue remains after 1.7.0 is released, please send request to reopen bug.
