### ISSUE TITLE
Bug: Freeze when Click  [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#235]
freeze when clicking the yellow or red 'bug' button

![image](https://user-images.githubusercontent.com/114440644/211591125-e3b3875e-7f7d-43a2-8833-d27d6c99c09c.png)

**Comment by Reyzerbit** [comment]
This appears to be resolved with the new codebase rewrite. ( See #228 ) If issue persists after version 1.7.0, please submit a comment to reopen bug.
