### ISSUE TITLE
Feature Request: Water Feature BOMs Auto Calculated [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#236]
Make BOM autofill for water features:

-pump
-granite*
-pump structure
-etc

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.1)
