### ISSUE TITLE
Feature: Bison Trays

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#238]
Add new 'category' within Bison for Trays (all 2"H elements)

Bison Trays are should default to Bison Silver (this is their standard and we've only deviated a handful of times)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.0)
