### ISSUE TITLE
Feature: Pre Designed Fire Pit

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#242]
Could we have a pop-up, like modified, to add the various components (burner, lid, media, etc) and have them pre-filtered by body type???

Especially if it's pre-filtered it would make us WAY faster and easier for the AEs to help configure new builds for pre-designed fire pits.

**Comment by Reyzerbit** [comment]
Why would this be any faster than using the already existing system of adding components from the receipts panel?

**Comment by Reyzerbit** [comment]
Being replaced in 1.7.1 with new child-structure system.
