### ISSUE TITLE
Bug: Fire Pit Detail Set [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#243]
Make burner window wider. I think the only thing it's not showing is 'small tank' on 351-1177 for example.

In stead of making the window wider you could also remove 'burner' and have the description start with the part #

![image](https://user-images.githubusercontent.com/114440644/211611294-3e27cd76-af9a-4a47-82cd-5278ee22899c.png)

--------------------------
Pan material type - Default: Stainless Steel 304
Pan material thickness - Default: 14 ga
--------------------------
Pan & Lid dimensions - Default: Burner dims (L+2"; W+2") if burner dims are in netsuite
--------------------------
Lid Material Type - Default: [same as body]
Lid Material Thickness - Default: .125" or equivalent 
Lid Finish Matches Body - Default: YES
Lid Height - Default: [Driven by media]
-Flush (1") [no media or glass media]
-Raised (3") [lava rock]
-Custom - enter value
--------------------------
**ADD:**

Glass Surround - did I give you the formula already??? 
-Height - static
-Length & width: Burner dims (L+2"; W+2") if burner dims are in netsuite

**Comment by Reyzerbit** [comment]
Being replaced in 1.7.1 with new child-structure system.
