### ISSUE TITLE
Bug: Ore3D Pulling Inactive BOM Components [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#244]
REF: 351-1065

I'm guessing there are more items impacted by what is causing this. 

![image](https://user-images.githubusercontent.com/114440644/211613687-c88c3055-7a9e-4029-9bfe-ec4d29e86b61.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.0)
