### ISSUE TITLE
Bug: 4100 Item Not Available [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#245]
Item 4100 not available in Ore3D. This should be in experlogix (BOM & Routings). If not, holler and I can help put that together. 

[PROPANE TANK HOLDER.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10386750/PROPANE.TANK.HOLDER.pdf)

O:\3 - CAD\CATALOG PRODUCTS\A4100 - Propane Tank Holder

**Comment by Reyzerbit** [comment]
Added into NetSuite as standalone item.
