### ISSUE TITLE
Note: Review Finish Coverage Rates [1.6.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#246]
When you are putting the rust patina in can we please review the finish coverage rates? 

It appears that we are calculating powder either at a very low coverage rate, or based on the sheet material which includes yield.

**Comment by Reyzerbit** [comment]
@MattIsrael is this still something we need to do?

**Comment by MattIsrael** [comment]
BOM appears to be allocating material correctly.

No further action needed. Please close out.

**Comment by MattIsrael** [comment]
BOM appears to be allocating material correctly.

No further action needed. Please close out.
