### ISSUE TITLE
Bug: Fuse Very Volatile - Crashes Often [1.7.0]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#249]
Crashed twice trying to create single, linear fuse edge. Fails trying to send error report as well. 

+Add Fuse Edge to Parent - CRASH (the default child was still in the parent, I was trying to add a second child)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.1)
