### ISSUE TITLE
Bug: Deconflict Last Item Price and Add Build Button [1.7.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#257]
![image](https://user-images.githubusercontent.com/114440644/217618889-bd805921-9f73-402c-9bc0-5f75c157a956.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
