### ISSUE TITLE
Feature: Make New Planters Use Shape Code Display Name for Default Title Instead of Product Name

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#259]
When a build is started as pre-design, then modified, the original pre-design part # needs to be removed from the Label/Title field. I would say that field can just become blank. 

![image](https://user-images.githubusercontent.com/114440644/217621750-2ef2d4a2-8ee3-4098-85b0-f55c594513a4.png)

![image](https://user-images.githubusercontent.com/114440644/217622439-a2bc8456-546b-48c0-9619-c439dd87a4a4.png)

**Comment by Reyzerbit** [comment]
Title field is never altered and attempting to implement title manipulation could cause a lot of issues, ESPECIALLY if left blank. Title is manually set, so if at anytime a product is no longer pre-designed, it is ideal for the estimator/sales rep to change it. Ideally a naming scheme can be made on a per-transaction basis.

**Comment by Reyzerbit** [comment]
Reopening as alternate concept was provided

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
