### ISSUE TITLE
Bug: Default Fuse Shared Wall Height to Linked [1.7.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#260]
Set default of Fuse Shared Wall Height to LINKED

![image](https://user-images.githubusercontent.com/114440644/217626662-ac426c94-66ce-4efa-b6cd-43a09304f7d8.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
