### ISSUE TITLE
Bug: Fuse Edging Pricing Issues [1.7.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#262]
I'm testing in the straight shape code.
Example Section: 55"x12"x12", 1" lip, .125 AL

- Are we adding material yield to these? Experlogix had ~15sf of aluminum while Ore3D has 12. Gussets are in the model - do we need to add them at 18" intervals? As long as it's in the pricing I'm fine with the model not being PERFECT. 
- Checking and unchecking Fabricated Lip or Linear Inch Model makes the parent price go up and up and up.
- Fabricated lip times seems pretty good. (85min)
- Formed lip time is very low. (16 min) - shouldn't this be a little more than half of the fab lip time?? Jarom guessed 45 min which would be in that same ballpark. 
- Child price/unit, and child total price are correct. Parent price needs review...
![image](https://user-images.githubusercontent.com/114440644/217632043-7b4cb2b0-0c47-4a14-af0e-24819bf7bb88.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
