### ISSUE TITLE
Feature: Bison on Product Selection Page

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#263]
This might not be as easy as it sounds in my head, in which case disregard. 

Can you remove the Bison items from the list of General Products? The Bison items would ONLY be visible if the Bison button (right of Bench) was clicked?

When we bid Bison it's either all or none so separating their products from Ore's products would play to that.

![image](https://user-images.githubusercontent.com/114440644/217635012-1097b2a0-69c7-4cf3-bb81-449f7629cc81.png)

**Comment by Reyzerbit** [comment]
Current search system is top down. The amount of coding work to change entire search/filter system to implement this request deemed too large.
