### ISSUE TITLE
Feature: Add buttons to Collapse/Expand All (Left Panel)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#265]
Add functionality to change all items to collapsed or expanded

![image](https://user-images.githubusercontent.com/114440644/217644005-c979afd5-dc45-4fa8-bf65-7dbc673590e5.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
