### ISSUE TITLE
Feature: Searching/Filtering Finishes

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#266]
I know you did some work to this recently - **I might just need education on how to best search.**

If I search for 'charcoal gray' I get 1 result - perfect!

If I search 'black' I get 19 results - too many. 
Searching 'ore black' doesn't seem to work. 

I think I asked before, but can we add some way of filtering things at a higher level? RAL, Custom, Bison, Premium....

PS  - what is the highlighting(different colors) indicating?
![image](https://user-images.githubusercontent.com/114440644/217648395-cf629b3f-c91a-402c-aa4a-3cbbc158281f.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
