### ISSUE TITLE
Bug: Rolling Bug/Enhancement List For Receipts Page [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#267]
[Receipts Reformat.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/10689819/Receipts.Reformat.pdf)

1. Work on reformatting per conversations. 
2. FYI I think Total Price (green) should actually be Total Cost. Total Price is the $ circled in red.
![image](https://user-images.githubusercontent.com/114440644/217649116-83090552-2ae6-4876-a1d3-adbaa9156309.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
