### ISSUE TITLE
Bug: RED Errors [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#269]
Please remove minimum height. Currently set to 6"H

Please remove lip depth constraint. Error "Must be no more than 1inches".  The lip depth just can't be greater than the width if formed. if fabricated we can do anythign. If the lip width and depth default to being linked it should eliminate any opportunity for error and we'll still have the flexibility we need for fabricated lips. 

**FYI - Most standard bowls, orbs, capsules and Yous have a lip depth that is > width.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
