### ISSUE TITLE
Bug: Reveal Dims Incorrect in NetSuite [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#270]
Reveal dims aren't pulling into NetSuite correctly.

![image](https://user-images.githubusercontent.com/114440644/217858802-976c2086-5a86-4706-87d3-231fe37a9f3b.png)

![image](https://user-images.githubusercontent.com/114440644/217858887-f6c858db-2ea8-40b3-be31-93b5cdbe096e.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.7.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.2)
