### ISSUE TITLE
Bug: Burner Descriptions [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#272]
Burner descriptions need to follow formatting below - need more info.

Point burner description to Experlogix Display Name in the item record.

**Comment by Reyzerbit** [comment]
This would require large data changes on the backend, deemed too much for benefit. Possible alternative, get Jake Drake to change "display name" to match for needed burners/BOM components
