### ISSUE TITLE
Other: Remove Extra Fields/Data

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#273]
Proposal: Remove 
-Reveal Length Inset
-Reveal Width Inset
-Lip Depth

I talked to Grif and he and I are in agreement that it would be preferable to remove the fields above from the proposal & sales order. At that point, I'd propose that we also remove them from within Ore3D for simplicity sake. Items are above. Expanded explanations are below.

The main theme is that estimating wants to provide enough of a description to qualify our price to the customer and let PM/CAD know of any 'big ticket items', but beyond that we want to give CAD the flexibility to work without constraints that don't have financial implications.

-Reveal Length & Width Inset: If we budget for the reveal (skid or skirt) to be full length and width it will allow CAD to detail the planters as needed. It's somewhat common for the reveal inset dims to be super complicated and it would just make more work for the estimator, PM and CAD to make and read qualifying notes on this. 

-Lip Depth: 99.9% of the time this will be equal to the width. I'm totally fine creating a note in the very rare instances where they are different. Those situations would likely require a note anyway.

**Comment by Reyzerbit** [comment]
Not planned to remove these fields at this time. CAD does not need to refer to these fields if they don't want to, but for future usages of Ore3D (future licensing plans), the fields will remain in place. Feel free to shoot me any questions in this regard. :)

**Comment by MattIsrael** [comment]
I talked to Shane last night and it came up in conversation that there might be a little miscommunication regarding some of these longer term goals. He said he would connect with us today, or Mike and I Monday to help get us all on the same page he is on.
