### ISSUE TITLE
Bug: Pre-Designed Item Dimensions [1.7.1]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#274]
Appears that most/all pre-designed elements are pulling in at 0.05" Aluminum opposed to their correct gauge.

I've also seen a couple lip dims that are incorrect.

Can you export a table of all Pre-Design item design traits and BOMs so I can review them with CAD and Supply Chain?

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/edit/1.7.4)
