### ISSUE TITLE
Bug: Item/Children (Non-Fuse) Descriptions [1.7.2]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#275]
Child items are not pulling into the description printing to netsuite.

![image](https://user-images.githubusercontent.com/114440644/217943655-800c8b52-3932-40e3-8733-b949c768f6f9.png)
![image](https://user-images.githubusercontent.com/114440644/217943725-53d64964-8b10-44ef-93c7-a86a4f6ea63f.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.3)
