### ISSUE TITLE
Bug: Fuse Parent Descriptions Need Development [1.7.2]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#276]
Most likely a meeting/conversation to discuss the mechanics to find a happy medium between ease of description creation and programming considerations. 

**Example:** 
[Label]
"L x "W x "H Linear Fuse Planter (& Edging)
Aluminum: .125"; Lips: 1.5"; Skid: 1"; Powder Coat Finish: TBD
[line break]
--- [options or custom description]

Explanation:
- Linear or Curved (if there is any curved)
- Product type eg Fuse Planter, Fuse Edging, or Fuse Planter & Edging
- Material type
- Material Gauge 
- Lip Width ([value if consistent] or 'Varies'

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.3)
