### ISSUE TITLE
Bug: 1116 - 2 Entries? [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#277]
I'm getting 2 product 'types' (?) when searching for "A1116"

Band, and Rectangle Band (2 images) both return the planter model 1116.
Haven't seen it do this before? 

![image](https://user-images.githubusercontent.com/114440644/218203221-1784b7b7-f750-4008-a352-298af93efdab.png)

![image](https://user-images.githubusercontent.com/114440644/218203260-efcddf92-ddc8-4bcd-93df-f5704187d635.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
