### ISSUE TITLE
Bug: Adding A1120 adds A1110 to Build [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#278]
This is a weird one. 

When you try to add an A1120 it adds an A1110 to the build list.

![image](https://user-images.githubusercontent.com/114440644/218205594-fb734f34-71d1-49ef-a5db-cfd0574f045d.png)

![image](https://user-images.githubusercontent.com/114440644/218205667-55a7af25-02d1-4623-8bfa-90fa55a471ce.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
