### ISSUE TITLE
Bug: Fab Lip Doesn't Go To Modified [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#279]
When starting with a pre-designed planter clicking Fabricated Lip doesn't turn it into a custom/Modified.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
