### ISSUE TITLE
Bug: Error Messages [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#280]
List gets too full. Should probably just scroll. 

Can these have the line # to the left of the error message to help track them down?

Example: (Line 62: Lip Width)

![image](https://user-images.githubusercontent.com/114440644/218518292-1d6eb5e4-3ad2-44fb-a026-a842818bf5c3.png)

**Comment by Reyzerbit** [comment]
Unable to do line number, as taking in to account child builds would make this very difficult. Messages does refine based on which builds are selected however, and it is recommended to use that feature. Scroll view will be implemented.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
