### ISSUE TITLE
Bug: Sheet BOM INCORRECT [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#282]
Specified sheet material wrong (listed on master pre-design bug list)

Sheet BOM too low. 

A1228-S:
Ore3D Calcs 9.84SF
Fab drawing specifies 13.19SF

A1211-S:
Ore3D Calc: 2.15SF
Fab Drawings: 2.67SF

A1217-S:
Ore3D Calc: 45.31SF
Fab drawings; 34.79SF

A1240-S
Ore3D: 29.67SF
Fab Drawing: 19.8SF

A1250-S
Ore3D: 27SF
Fab drawings: 18.15SF

A1251-S
Ore3D: 37.89SF
Fab drawing: 26.88SF

A1252-S
Ore3D: 58.32SF
Fab Drawing: 39SF

~~A1223-S~~
~~Ore3D: 35.15SF~~
~~Fab Drawings: 25.61SF~~
1223 SqFt of sheet metal actually is ~36

**Comment by Reyzerbit** [comment]
Partial implementation in 1.7.4. Need to discuss how Facet SqFt will be implemented.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
