### ISSUE TITLE
Bug: ERRORS on Crash Recovery [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#284]
RED Errors 'resolve' after crash and recovery of open proposal.

63 (from before crash)
64 (from after crash)

**update**
If you add a new line it resolves the error as if it can only have 1 red error (pic 2)

![image](https://user-images.githubusercontent.com/114440644/218522003-58657cbc-71a6-4ec0-8e3b-61827822827f.png)

![image](https://user-images.githubusercontent.com/114440644/218523199-d6800f95-cede-40d2-bd55-c22a0343993b.png)

**Comment by Reyzerbit** [comment]
Possibly due to recalculation errors. Simple change dimension back and should resolve.
