### ISSUE TITLE
Bug: Fuse Moved to Bottom Line # [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#285]
After saving the fuse items were rearranged to bottom of item list. 

![image](https://user-images.githubusercontent.com/114440644/218533582-296a7f26-54b1-4d48-9f5d-12070a28bba9.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
