### ISSUE TITLE
Bug: Sheet Metal (.050" AL) Pointing to wrong NS Item [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#286]
.050" Aluminum is pulling in .5" aluminum. 

![image](https://user-images.githubusercontent.com/114440644/218560172-bc54534b-cb37-4092-9bcf-820446d7e8d1.png)

**Comment by Reyzerbit** [comment]
Resolved as NetSuite issue
