### ISSUE TITLE
Bug: Sheet Metal (BOM) pulling into item description [1.7.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#287]
Sheet metal and other BOM items should not be pulling into item descriptions:

![image](https://user-images.githubusercontent.com/114440644/218560513-01260e4f-08b2-4da8-b6e2-8340f75e7eac.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/1.7.4)
