### ISSUE TITLE
Bug: Zinc Patina Not Adding Cost [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#288]
https://3619299.app.netsuite.com/app/common/item/item.nl?id=354433

![image](https://user-images.githubusercontent.com/114440644/218567114-b2e0cb37-3e66-4bd1-bf81-356f09c51d01.png)

**Comment by Reyzerbit** [comment]
Refresh pricing data.
