### ISSUE TITLE
Bug: A1002 Identified as A1027 [1.7.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#289]
Was a A1002 (with skirt). When I updated to skid, to test whether it would re-identify as a predesigned it did, but as a cove pomo

![image](https://user-images.githubusercontent.com/114440644/219072189-b141958e-24c1-49ae-9fb1-15eff8eeb5e8.png)

**Comment by Reyzerbit** [comment]
Resolved as misinput.
