### ISSUE TITLE
Feature: Add detail to Build Summary (left panel)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#290]
Can we add a little more info to the build in the left panel? 
 Being able to quickly scan for finishes and options (item# is acceptable ) would allow us to review a proposal much more quickly. 

Image

Can we add L, W, H to modified planters in addition to the info above?

Image

**Comment by Reyzerbit** [comment]
If there's something you would like to replace, let me know. But there's no room for anything new without eliminating something else.

**Comment by MattIsrael** [comment]
There is no room for either? 
Can we make room? 

I'm just trying to imagine a process for the estimators to quickly review their proposal without going back to netsuite or going line by line (we would do that for a more indepth review).

**Comment by Reyzerbit** [comment]
Good UX design is about not over-complicating the information in a specific location. We have already crammed SO much into the tiles on the left, that adding anything new begins to eliminate good UX design. If you feel one thing is more important than another, we can look into replacing it. Otherwise, no additional data will be added.

**Comment by mxidis** [comment]
Alternative: Create Overlay display system that allows users to select datatypes from a dropdown and overlays that data on top of the current left-pane.

**Comment by MattIsrael** [comment]
Can we make a new 'tab' on top? 'Summary' (would essentially show the netsuite descriptions and columns)

Can you help me think of a way that users can perform a review of items, while still in Ore3D and not going line by line.

**Comment by Reyzerbit** [comment]
That's essentially what Mike is proposing, but using a checkbox.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
