### ISSUE TITLE
Feature: [Admin Feature] Price Pre-Design as Custom

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#291]
Is there a way, for admins only, we can disable the feature where Ore3D identifies pre-designed pricing? 

I would use this feature to re-price the pre-designed planters when we get to that point. 

If it could be a setting that would allow me to have a single proposal with all standards I would be able to:

-Verify pre-designed pricing when the toggle was off
-price pre-designed without having them pull in the 'set' price when the toggle is on

I'm picturing this on the top bar of Ore3D  or something so I had this single toggle within Ore3d(not in netsuite like the price override) but not at the line item level - make sense?

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.8.14](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.14)
