### ISSUE TITLE
Bug: Modular Corners Missing Minor L and Minor W [1.7.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#294]
This might be related to the bug/crash that was just submitted. ( #293 )

![image](https://user-images.githubusercontent.com/114440644/219081965-826ff34b-73a1-4ee4-beff-44395758baaf.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
