### ISSUE TITLE
Bug: Existing Tag Not Populating [1.7.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#295]
Existing Tags are not populating.

![image](https://user-images.githubusercontent.com/114440644/219083139-711c648a-78ae-4eae-95bd-3c3cd71f6017.png)

![image](https://user-images.githubusercontent.com/114440644/219083268-bd923a92-34dd-4494-bc45-2ddeb131c465.png)

When second tag was added:
![image](https://user-images.githubusercontent.com/114440644/219083513-45e37266-600e-4ea7-9443-cff7363b94ab.png)

**Comment by Reyzerbit** [comment]
Looked into it, the tags are populating, you just need to scroll. I'm adjusting the size of the window in the next version so it's more easily visible, but the tags are there.
