### ISSUE TITLE
Bug: Tag Selection Overlap Conflict [1.7.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#296]
![image](https://user-images.githubusercontent.com/114440644/219083755-a2980b1d-d8ff-4c52-96c9-35bc8d0937fa.png)

check marks overlap the tag

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
