### ISSUE TITLE
Bug: Lip Link Doesn't Update Values [1.7.4]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#297]
Please set Lip and Reveal links to default on. I think adding a custom rectangle put these in as 'off'.

![image](https://user-images.githubusercontent.com/114440644/219086136-8a90e8b1-1f10-4a28-8fc0-017610dde08c.png)

when you click link it doesn't override the other value

![image](https://user-images.githubusercontent.com/114440644/219086784-4590753f-e3ec-4338-88fd-569d2a98ea2c.png)

**Comment by Reyzerbit** [comment]
Specs are linking on default, when added to proposal for the first time, but not saving between sessions. 1.7.4 will include linkage saving between sessions. The no immediate override is intentional, so as to prevent accidental click-overwriting.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
