### ISSUE TITLE
Feature: Edit Color/Name of Existing Tags

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#299]
Is there a way we can edit existing tags, like color, after it's been created. 

Can we change how tags are removed? It's a little too easy for remove tags (just by clicking on them). 
++Maybe you open the 'tag' pop-up to remove/delete tags -- you can multi-select when working with tags right?

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
