### ISSUE TITLE
Feature: Fuse Edging - Hide Reveal Inputs

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#300]
Can you move all Reveal fields into the Additional Dimensions for Fuse EDGING?

edging doesn't and can't have a reveal.

**Comment by Reyzerbit** [comment]
Planned implementation in 1.7.4. Once it is implemented, old edging with still have reveal specs, but any new edging created here on out will not.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
