### ISSUE TITLE
WO Generation Process: Child WO's

### ISSUE THREAD

**Issue by mxidis** [Ore-Design/Ore-3D-Reports-Changelog#301]
1. Create a grouping system that allows estimators to show how WO should be generated based on how they estimated it
2. Allow Child Items to be selected to create WOs
- Those child items should 'take' material and labor away from the parent WO
- Once a parent WO is generated, children should be locked from WO generation
- If a child WO is created the parent should include the child subassembly as a component
- set the 'isphantom' toggle according the child WO generation

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.5)
