### ISSUE TITLE
Bug: Fuse Rectangle Split  [1.7.5]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#304]
Fuse Rectangle Split
Test Dims: 100"x100"x36"H

Split Sections: 2x2 (should be 4x 50x50)

![image](https://user-images.githubusercontent.com/114440644/219498741-559dd5d7-9cbe-4223-855f-5078af607a13.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.7.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.6)
