### ISSUE TITLE
Feature: Fire Pit Media

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#307]
Can we add recommended media quantities based on pan size? 

This use to be automated in the popup, but we lost that functionality with the children. It could just be provided values under the Additional Dimensions tab?
(estimator would still need to add the option and qty manually, Ore3D would just help by doing the calcs.

Lava Rock: xx CF
Glass Rock: xx lbs

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.8)
