### ISSUE TITLE
Bug: Drip Tray Fab Time Too Low [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#313]
![image](https://user-images.githubusercontent.com/114440644/221303347-2efee4d3-590c-4203-8b57-da96a941c9ee.png)

![image](https://user-images.githubusercontent.com/114440644/221303515-c799b79f-e0c0-4a79-a249-797b1c8b1093.png)

**Comment by Reyzerbit** [comment]
Issue was caused by database issues. Now resolved.
