### ISSUE TITLE
Bug: Junction Box [1.7.6]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#318]
Revise Jbox routings to default routings below. Depts not listed below will continue to calculate as they are currently programmed. 

CAD: 0
Finishing*: 0
Packaging: 0

*We do not finish a jbox so it shouldn't add powder or finish labor.

**Comment by Reyzerbit** [comment]
Unable to replicate. Please get me more info otherwise I will close bug in 7 days.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.8)
