### ISSUE TITLE
Feature: Fuse Edging [Anchored]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#320]
Can you please add a checkbox to fuse parent that will allow us to modify the description going to netsuite?
ONLY APPLIES TO FUSE EDGING

If box is checked add 'Anchored' - see below

Example:
[Label]
"L x "W x "H Linear Fuse **Anchored** Edging
Aluminum: .125"; Lips: 1.5"; Skid: 1"; Powder Coat Finish: TBD
[line break]

![image](https://user-images.githubusercontent.com/114440644/221904956-99f8fc26-557a-4097-b2ef-a387ebcc07b5.png)

**Comment by Reyzerbit** [comment]
Please clarify: does this change the description for the parent, or for the edging itself?

**Comment by MattIsrael** [comment]
This changes the description that prints to NetSuite.
Child should driver parent?

**Comment by Reyzerbit** [comment]
Fuse edging no longer has a way to distinguish between anchored and un-anchored edging, as requests were made to be able to set edging width manually.

**Comment by MattIsrael** [comment]
Can we have a checkbox that simply modifies the description? That is how experlogix currently works and we have no issues with that. 
*we do need the ability to set the width dimensions manually. Occasionally we'll have a unique condition sold and engineered.
