### ISSUE TITLE
Feature: Default Labels

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#321]
Can we change the Default Labels on Fuse ("U_PRNT") so we don't NEED to update them? 

Modified - What you have is good!

Fuse Edging - "Fuse Edging"
Fuse Planter - "Fuse Planter"

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.7](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.7)
