### ISSUE TITLE
Feature: Retain 'Pre-Split' Fuse Dims

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#323]
Can we retain the 'pre-split' dimensions for fuse somewhere? It doesn't need to be editable, but somewhere. 

Could those dims live where the red line is? I remember you saying we had limited real estate in these boxes

![image](https://user-images.githubusercontent.com/114440644/221907989-7d1bf958-2f1a-4967-b807-2a2d2301e59f.png)

Happy to discuss other options for locating this information.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.3)
