### ISSUE TITLE
Bug: Change 2nd Tier Price Field

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#324]
Please direct pricing to look at:

1. Ore3D Override Price
2. Purchase Price

*Confirmed with supply chain*
![image](https://user-images.githubusercontent.com/114440644/221924317-27f71340-ec47-48f4-aa76-1205ce3c7b1d.png)

**Comment by Reyzerbit** [comment]
This is pending decision from pricing meeting to verify how we will be moving forward.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.3)
