### ISSUE TITLE
Feature: Curved Fuse Edging & Planters Default Lips

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#327]
Curved Fuse Edging
Curved Fuse Planters

Please set the Fabricated Lips=yes to default.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.8)
