### ISSUE TITLE
Bug: Fuse: Is Rounded Curve - Changed Finishing

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#328]
This checkbox should NOT change finish labor. (should not change anything)

**See related feature request. 

![image](https://user-images.githubusercontent.com/114440644/222190832-43526dbd-37ff-4d45-ac43-e24bf21dc072.png)

![image](https://user-images.githubusercontent.com/114440644/222190949-657b369c-b30f-4c70-a322-ffbf40d7d66d.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.8)
