### ISSUE TITLE
Bug: Large Fuse Planter Split

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#330]
When splitting fuse planters that are >2 sections wide and >2 sections long:

- Splits into too many children (should be 1 child per 'split')
- Splits into INCORRECT sections qty

![image](https://user-images.githubusercontent.com/114440644/222198036-b6c7ca1f-42b1-498e-bf1a-a76b4a4935d3.png)

![image](https://user-images.githubusercontent.com/114440644/222198144-1ab91b9b-c2b7-4d2d-a68b-09907be36c6e.png)

**Comment by Reyzerbit** [comment]
Split looks correct to me. Talk to me for questions.

**Comment by MattIsrael** [comment]
Split function needs to create planter section array (Length x Width)=section qty.

![image](https://user-images.githubusercontent.com/114440644/222219409-4589f389-6463-42ec-8579-8d1fe11da1b7.png)


All sections to receive identical pricing.
Sections budgeted to receive full height 'interior' walls. PCs will manipulate this if/when needed - rare. 


In the event we need to price a 'donut' we would price it as a single long rectangle but describe it as the outside dimensions - this is why our child dimensions don't go into the netsuite description.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.8)
