### ISSUE TITLE
Feature: Allow Custom Component To Be Added Without Margin [1.7.7]

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#332]
CUSTOM COMP AUTOMATICALLY ADDING MARGIN. 
 
![image](https://user-images.githubusercontent.com/114690243/222491163-712d4e4b-6817-4961-b225-30695f36bded.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.7.8](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.7.8)
