### ISSUE TITLE
Bug: [Modified Pomo] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#334]
Adding to the width makes the price go down:
![image](https://user-images.githubusercontent.com/114690243/222504377-6aaac994-b970-43b5-91e7-1ce536368d35.png)

![image](https://user-images.githubusercontent.com/114690243/222504443-e306b61f-0f1c-4a78-a9a2-b1329cb5e680.png)

**Comment by Reyzerbit** [comment]
Modified Pomo's are currently very fragile. We don't have a system to adjust calculations for POMO pricing, but that is on the todo list ( see #292 ). Closing as technically a duplicate.
