### ISSUE TITLE
Feature: Option for custom name field to be left blank.

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#337]
**Issue:**
A name for a planter isn't always required. Whereas, adding the name to the custom field means needing to add the name to the takeoffs as well. 

**Solution:**
Option to leave the name field blank.

**Comment by Reyzerbit** [comment]
It is not possible to leave the name field blank. For that reason the name field is auto populated with the generic name of the product.
