### ISSUE TITLE
Bug: [Incorrect metric for LED Lip Lighting ] [Ore3D Version (1.7.8)] 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#338]
**Bug:**
LED Lip-Lighting is being measured via Linear Inch. 

**Recreate:**
1. See Item number [310-1012] 

**Expected Behavior:**
LED Lip-Lighting should be measured via Linear Foot.

**Comment by MattIsrael** [comment]
UOM correct in NetSuite, but incorrect(doesn't match) in Ore3D

![image](https://user-images.githubusercontent.com/114440644/223223694-693b8580-ef5f-4789-a769-1caefd3aca1d.png)
![image](https://user-images.githubusercontent.com/114440644/223223762-78b7fcbb-e3e6-41ac-a78e-1a7e0353a90f.png)

**Comment by Reyzerbit** [comment]
Issue was due to mismatching NetSuite lists. Issue is now resolved. NetSuite UOM now matches Ore3D correctly.
