### ISSUE TITLE
Bug: Mouse Cursor doesn't always appear in customer notes field [1.7.8]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#339]
**Bug:**
Mouse cursor doesn't always appear in customer notes field.

**Recreate:**
1. Type misc. note in customer notes field 

**Expected Behavior:**
See cursor location 

**Additional Context/Questions:**
Issue doesn't prorogate to internal notes section.

**Comment by Reyzerbit** [comment]
Unable to replicate, may have accidentally fixed it without realizing in 1.8.1.
