### ISSUE TITLE
Bug: Planter weight doesn't calculate in steel gauges [1.7.8]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#340]
**Bug:**
Planter weight doesn't calculate in all gauges options for both mild steel Corten.  

**Recreate:**
1. Add planter and change material to a gauge option.

**Expected Behavior:**
Add weight to planter when changing gauge option.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
