### ISSUE TITLE
Bug: Ore3D crashes when selecting receipts panel of Red or Yellow error page [1.7.8]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#341]
**Bug:**
ORE-3D crashes when selecting receipts panel of Red or Yellow error page. 

**Recreate:**
1. Click on red or yellow error number.
2. Click receipts panel. 

**Expected Behavior:**
ORE-3D to not crash.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
