### ISSUE TITLE
Quick Review: LED NetSuite Item Reconcile 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#343]
Just give this a quick eye to make sure I did this correctly.

Per JD in supply chain
Reason: duplicate LED face light items

310-1011 - Ore3D Display [unselected]
400-7001:
-ORE3D DISPLAY [selected]
-Override Price added
-Ore3D UOM: Linear Inch
-Ore3D BOM Type: LED Lights (**This is different from 310-1011 which was 'Other'**)

**Comment by Reyzerbit** [comment]
Looks good :)
