### ISSUE TITLE
Feature: Drain Hole Description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#345]
Currently "Includes Drain Holes" is toggled on/off with the check box. Can you change that to:

Drain Holes [Y]
Drain Holes [N]

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
