### ISSUE TITLE
Bug: Option Items/Components Not Adding to Description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#346]
Option components are not adding the to NetSuite description - ask Matt if you need a description template
**Also doesn't work if options are added to a child - ex. casters added to a drip tray**

![image](https://user-images.githubusercontent.com/114440644/223226332-ea394d02-216f-4578-a0e6-c0508635ae04.png)
![image](https://user-images.githubusercontent.com/114440644/223226367-5d71f08d-60c6-4e0f-a304-fe0e7b7f7a78.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
