### ISSUE TITLE
Bug: Description Not Showing up until I select another item. 

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#348]
The description of planters does not show up until another item is added. 
![Description Bug 03062023](https://user-images.githubusercontent.com/114699058/223229847-46f92dc5-d8db-4ea0-85ce-7aaf329c80fb.PNG)

**Comment by orepf** [comment]
The proper description of a predesigned planter does not show up until after another item is added to the proposal. 

So if I select a trapezoid, it shows as a taper with weird dimensions. Then once I add another item the description goes to what it should be.

**Comment by Reyzerbit** [comment]
Possibly fixed with other 1.8.0 changes.
