### ISSUE TITLE
Bug: Modified Bison Description Not Updating

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#350]
Modified Bison still described as 'predesigned' and has original part #. 

custom bison not available on 'add product screen'

IF MODIFIED:
Remove part # from label - can be replaced with Modified Bison or something similar to Ore's products. 
"Predesigned" needs to be removed from description after dimensions, but "Bison" can stay.

![image](https://user-images.githubusercontent.com/114440644/223246524-fbaba4bc-0713-498e-886f-9510288d84bc.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
