### ISSUE TITLE
Bug: [No cost added for [200-1002] & [200-1026] adjustable feet] [Ore3D Version (1.7.8)]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#351]
**Bug:**
No cost added for [200-1002] & [200-1026] adjustable feet. 

**Recreate:**
1. Add [200-1002] to proposal. 
2. Add [200-1026] to proposal. 

**Expected Behavior:**
Add cost for adjustable feet.

**Comment by Reyzerbit** [comment]
This is an issue to bring up with Matt and the Supply Chain team, not a bug with Ore3D.
