### ISSUE TITLE
Feature: Netsuite steel thickness description. 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#353]
ORE-3D currently defines steel thickness in gauges and decimals. Netsuite descriptions should mirror ORE-3D. 

 
![image](https://user-images.githubusercontent.com/114424580/223275503-e24c3d90-47d4-4191-8d37-b14404ee82e8.png)
![image](https://user-images.githubusercontent.com/114424580/223275593-c32e63ad-a612-4983-9342-46ee1bd5a056.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
