### ISSUE TITLE
Bug: Description overlaps itself in Messages Panel [1.7.8]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#354]
Description overlaps itself. 

![image](https://user-images.githubusercontent.com/114424580/223276203-511bc577-e0bd-43b8-8000-eefd14aaf630.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
