### ISSUE TITLE
Bug: Routing Text Changes

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#355]
Not sure if this impacts other things than the capitalization?

![image](https://user-images.githubusercontent.com/114440644/223483087-58f6ad93-17e0-4859-b7ad-425c591d94c0.png)
![image](https://user-images.githubusercontent.com/114440644/223483153-8c3cb895-b966-4f3d-ad17-360d7f5fd03d.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)
