### ISSUE TITLE
Bug: Fuse Rectangle>Corner No Inner Walls

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#358]
Fuse Rectangle> Corner

No inner walls. More closely looks like edging with a giant base.
![image](https://user-images.githubusercontent.com/114440644/223493941-b1641c28-7a01-4818-a730-75e4f22b10e4.png)

**Comment by Reyzerbit** [comment]
Planned to simply remove the corner type for fuse rectangle. Is there anything on your end that would discourage this?

**Comment by Reyzerbit** [comment]
Closed as expired.
