### ISSUE TITLE
Bug: Double Grove incorrect height [Ore3D Version (1.7.8)]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#359]
I believe the 1024 double grove is in as the wrong dimensions. Should be 28"h, currently in at 27"h.

**Comment by jjohnson2525** [comment]
Also, see 1023 single grove.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
