### ISSUE TITLE
Bug: S1004 Duplicated Label [1.8.0]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#361]
S1004 duplicated label. When added to proposal it will make taper custom. 

![image](https://user-images.githubusercontent.com/114424580/223862752-714038ee-bda4-4a4c-8896-8f53274f235f.png)

![image](https://user-images.githubusercontent.com/114424580/223863023-5f0e33cb-f47b-47ca-a7e6-d57a5a78531a.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
