### ISSUE TITLE
Glass Surround Pricing Placeholder

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#362]
I tried to tie some of this back to actual routings, but this is just a bandaid to get us live. We'll have to refine this with full BOM & routings later.

![image](https://user-images.githubusercontent.com/114440644/223865546-2f6c9087-1c8b-4628-a113-dc4cb381d3ff.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.0)

**Comment by MattIsrael** [comment]
Please review formulas. Pricing is not where we want it - might be a flaw with my formulas
-not pulling burner dims in -- sheet metal & fab, finish  time impacted

- I will add price to 352-1012 (clips)
Not adding glass or price for glass.

![image](https://user-images.githubusercontent.com/114440644/224367423-55d815e2-4fac-4941-8a3f-7b0e2a0a16f1.png)

**Comment by Reyzerbit** [comment]
Pricing is exactly as formula specified, with the exception of glass. Glass must be added manually. Pricing for clips needs to be added to NetSuite.
