### ISSUE TITLE
Bug: [CRASHED WHILE OPENING 41434] 

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#367]
![image](https://user-images.githubusercontent.com/114690243/224741852-1f8108d3-3618-4e4b-869e-5be9049e97a1.png)

**Comment by daniel11088** [comment]
Tried it again with same result

**Comment by Reyzerbit** [comment]
Per my notification in Teams: old estimates may no longer work and even crash Ore3D, due to a massive change that was implemented. Please create a new proposal to continue testing.
