### ISSUE TITLE
Feature: Change to Split Fuse Screen

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#371]
Please change SF to CF for the proposed section size:
Field should be "Volume:" [UOM = CF]

![image](https://user-images.githubusercontent.com/114440644/224744575-42897a32-71e9-4851-b8a3-4810a29bc9c1.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
