### ISSUE TITLE
Bug: LED LIGHT MULTIPLE ISSUES

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#373]
LED TOE KICK ADDED TO FUSE CHILD

- LED UNIT OF MEASURE NOT CORRECTED TO LF
- 0% MARGIN -CORRECT
- TOTAL COST SEEMS TO BE INCORRECT

![image](https://user-images.githubusercontent.com/114690243/224752192-e9580dbb-6b05-4bd1-99c9-be40b790db45.png)

![image](https://user-images.githubusercontent.com/114690243/224752228-6646ef42-c2a3-4e11-935b-4602b3253ece.png)

**Comment by Reyzerbit** [comment]
Issue had to do with NetSuite organizational data. Now resolved.
