### ISSUE TITLE
Feature: OPTION TOTAL QUANTITY OVERRIDE

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#374]
SOLUTION FOR DISPORPOTIONATE OPTION DISTRIBUTION ACCROSS FUSE CHILDREN. 

EX:
FUSE PLANTER MIGHT ONLY HAVE 1 IRRIGATION SLEEVE.
LED OFTEN NOT EQUAL LENGTH OF FUSE CHILDREN. (CORNERS VS STRAIGHT)

![image](https://user-images.githubusercontent.com/114690243/224753483-7fba47e0-f337-4b3b-b383-30afbbb566f4.png)

**Comment by Reyzerbit** [comment]
Please talk to me about how to do this in the already existing system. Creating a new way to fix this isn't worth the possible bugs and issues when a good-enough system already exists.
