### ISSUE TITLE
Bug: [ORE-3D Crash after saving] 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#382]
**Bug:**
ORE-3D will crash on re-login to proposal after saving to net suite. See #42366. I added IRR sleeves and drainage fittings before save cycle, these add-on options may be cause.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
