### ISSUE TITLE
Bug: Curved FUSE length Not informed by math equation

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#383]
The length of the curved fuse say it needs to be 10 greater than the width. But that doesn't really work because if a customer wants a planter that has a slight curve and the width and the length should be able to be the same. 

equation to use:
Circumference of an annular sector:cr,R,θ=R⋅(θ+2)+r⋅(θ−2) can't equal negative number or 0.
![image](https://user-images.githubusercontent.com/114699058/224766499-13293079-db76-4418-81a9-6b2ddc221541.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
