### ISSUE TITLE
Bug: Description - fuse child vs fuse parent

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#385]
Please make fuse parent(what prints to netsuite) to reflect the same description format as custom planters and fuse children. The formatting of our descriptions should largely be identical to each other.

Child:
![image](https://user-images.githubusercontent.com/114440644/224764720-814ef49e-9467-4853-953b-7704874131dc.png)

Parent:
![image](https://user-images.githubusercontent.com/114440644/224764816-a67ac27c-61bc-4080-aebd-6c5c6621c7bd.png)

**Comment by MattIsrael** [comment]
Please make fuse parent(what prints to netsuite) to reflect the same description format as custom planters and fuse children. The formatting of our descriptions should largely be identical to each other.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
