### ISSUE TITLE
Bug: Fuse Rectangle Type Resets After Split

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#386]
Fuse Rectangle Type resets after split.

![image](https://user-images.githubusercontent.com/114440644/224787752-2a03a869-9293-436b-b956-3a164b468705.png)

![image](https://user-images.githubusercontent.com/114440644/224787918-a0e54fcb-cf39-4af1-983c-fcc234fb719f.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
