### ISSUE TITLE
Bug: Fuse Revert Split

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#393]
Revert Split appears to not work if the parent is a duplicate.

you are allowed to click the 'revert' arrow. Upon doing this the arrow disappears, but the split is not reversed.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.1)
