### ISSUE TITLE
Feature: QUANTITY DISCOUNT NOT BEING APPLIED

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#396]
![image](https://user-images.githubusercontent.com/114690243/225424654-8ce0cce6-9557-430a-a684-b67d2dc14fd8.png)

![image](https://user-images.githubusercontent.com/114690243/225424760-2efae600-5f02-4101-a3b9-55538a04239e.png)

**Comment by daniel11088** [comment]
CAD TIME FOR 1 DIVIDED BY QUANTITY.
THE CAD TIME FOR 2 SHOULD BE 55.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
