### ISSUE TITLE
Bug: description not matching

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#397]
The description in ORE 3D is not matching in Netsuite. In this case, the Netsuite description shows 2" blade lip but in Ore3D there is no lip. 

![image](https://user-images.githubusercontent.com/114690243/225430874-c4c34437-d719-4386-af40-b830705814d7.png)

![image](https://user-images.githubusercontent.com/114690243/225430914-07ce2c36-2e79-40de-882a-67b218c41850.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
