### ISSUE TITLE
Bug: Finish: To Be Decided (None) 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#403]
Please adjust "Finish: To Be Decided (None)" to "Finish: To Be Decided". 

99.9% of items requires a finish before being shipped out. Having "None" may lead the customer into thinking that items can be shipped without a finish. I think this would be a good quality of life change.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
