### ISSUE TITLE
Feature: Remove "Addons:" from description

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#404]
Remove "Addons:" and "Notes" from description. "Addons" is misleading/confusing when no addons are present in the proposal.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
