### ISSUE TITLE
Bug: fire feature thickness

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#406]
Is there a way to change material thickness of custom fire features to .188 automatically? 

![image](https://user-images.githubusercontent.com/114690243/226722393-142f6938-d7bf-490f-9228-131404840bff.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
