### ISSUE TITLE
Feature: Description field enlarge request 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#407]
Current description field doesn't give us full visibility of item part numbers being priced. Requesting an ability to see full description so we can see specified part numbers. See example, I'm not able to distinguish the differences between the highlighted burners inside ORE-3D program. 

![image](https://user-images.githubusercontent.com/114424580/226942605-0a412b9a-daed-42da-a478-d689cb567dd7.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
