### ISSUE TITLE
Bug: CLONE/COPY DOES NOT DUPLICATE NOTES

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#408]
![image](https://user-images.githubusercontent.com/114690243/226960684-9d3f3830-f553-4ac3-8d92-72ef10b79bd7.png)

![image](https://user-images.githubusercontent.com/114690243/226960994-cb8692b9-ccaa-4750-af79-5114700ffa85.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Update 1.8.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.2)
