### ISSUE TITLE
Bug: Parent Pricing not Updating after Child Routing Time Override

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#410]
The parent price does not update when children routing time is overriden.

![image](https://user-images.githubusercontent.com/114699058/227256847-7c9a76df-5d3a-4a0f-b150-c49d375199f1.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.3)
