### ISSUE TITLE
Bug: Not Able to Create Custom Aluminum and Mild Steel Placeholder Components

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#413]
Get an an error when trying to create a special order component. 

![image](https://user-images.githubusercontent.com/114424580/227304866-e223de44-309f-4dfc-b55b-5911dd9c890b.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.3)
