### ISSUE TITLE
Feature: Pricing Override

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#416]
Can we change the pricing override to be based on user permissions opposed to the checkbox in netsuite? 

The checkbox is very cumbersome to use.

**Comment by Reyzerbit** [comment]
Setting override to be based off permissions means that whoever the new director of sales is would have to open Ore3D and input the override for you. It also means that if one person with a permissions level opens it with override and another person who doesn’t have that permission opens it, it would break. 

TL;DR switching to permissions is not a smart way to go.
