### ISSUE TITLE
Bug: SAVING A PROJECT IN ORE3D REMOVES DISCLAMERS AND ANY OTHER LINE ITEMS IN NETSUITE

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#417]
No picture for this bug but the disclaimers and other notes are critical for our bids.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.3)
