### ISSUE TITLE
Bug: Price of Bowl not in ORE3D

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#418]
Price of Bowl not in ORE3D

![image](https://user-images.githubusercontent.com/114699058/228011166-bd9b953e-6863-4d2f-8095-2516e17129fa.png)

![image](https://user-images.githubusercontent.com/114699058/228011256-896df7c8-b18b-4e61-952d-f7d48566ebbd.png)

![image](https://user-images.githubusercontent.com/114699058/228011346-b038a3f3-0697-4769-ad1e-1218d1908eb3.png)

**Comment by Reyzerbit** [comment]
This is a concern to bring up with Matt and the operations team.
