### ISSUE TITLE
Bug: QUANTITY DISCOUNT AND FUSE PARENT ROUTING CHANGES NOT WORKING

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#424]
CAD time is not being adjusted when quantity changes.

When CAD is adjusted in parent, the total does not change. CAD time has to be adjusted in each child separately to adjust total price. 

![image](https://user-images.githubusercontent.com/114690243/228615012-98fc8f09-7d80-4992-a62b-19b2b68b342e.png)

![image](https://user-images.githubusercontent.com/114690243/228615193-e8c0496e-66b3-423c-b1ba-df92cb82f454.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.3)
