### ISSUE TITLE
Feature: ADJUST FUSE CHILDREN FROM PARENT

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#425]
Is it possible to adjust things like lip width, color. etc in the parent that can trickle down to the children like it does in Experlogics?

**Comment by Reyzerbit** [comment]
Not really worth the amount of coding changes it would take. Recommended alternative is multi-select.

**Comment by MattIsrael** [comment]
Multiselect would be a great alternate solution. I don't believe we are able to multiselect fuse or fuse children.

Do you have a bug open for that, or can we reopen this with multi-select as the planned solution?

**Comment by Reyzerbit** [comment]
Multiselect functions all work properly. Shift-click and ctrl-click work within fuse parent hierarchies. If you want to select fuse children and non-fuse children at the same time, use the circle checkbox next to each build tile.
