### ISSUE TITLE
Feature: Make Disclaimers Searchable

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#428]
Make disclaimers searchable. 

I think we can delete a bunch of them. If someone can email me the saved search I can review and comment on which ones can go away.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.4)
