### ISSUE TITLE
Bug: Disclaimer Formatting After Save

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#429]
After save, close, reopen. Please deconflict disclaimer with item.

(it fixes it self when you click on it)

![image](https://user-images.githubusercontent.com/114440644/229542000-0e3e9ded-8130-4593-87d8-e247e4177875.png)

**Comment by Reyzerbit** [comment]
Unable to replicate on any other orders, and due to the fact that this order was loaded in Experlogix after submitting the bug, I can no longer test this specific order it in Ore3D. Please recreate this bug and explain how it is achieved, otherwise bug report will be closed in 7 days.
