### ISSUE TITLE
Bug: Ore3D DELETES FUEL SURCHARGE!

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#430]
Upon save of Ore3D it deletes the Fuel Surcharge in Ore3D and thus NetSuite.

**Comment by Reyzerbit** [comment]
Please explain how you are adding the fuel surcharge, as currently we have no implemented method of doing so.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.4)
