### ISSUE TITLE
Bug: Unreadable error messages

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#432]
Unable to expand error message. Is there a way to expand the message so we can read it?

![image](https://user-images.githubusercontent.com/114690243/229560403-ded2b995-9e68-43e3-843f-cb3c928ed4be.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.4)
