### ISSUE TITLE
Bug: FUSE DESCRIPTION INCOMPLETE WHEN TRANSFERED TO NETSUITE

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#433]
The custom components and Add-ons in fuse children are not being transferred to Netsuite.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.4)
