### ISSUE TITLE
Feature: Complete Custom Band Planter Calculations

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#435]
![image](https://user-images.githubusercontent.com/114690243/229890365-5f064259-aa62-45d6-b9ab-2414e07ff840.png)

![image](https://user-images.githubusercontent.com/114690243/229890679-2f2a512d-68e5-45fa-8498-5f4cc44e5477.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.5](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.5)
