### ISSUE TITLE
Bug: Fuse CAD Labor

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#444]
CAD time is dividing when the fuse is split. Parent qty is the only thing that should impact cad time.

![image](https://user-images.githubusercontent.com/114440644/230466033-60571553-3420-4c69-a379-793f115ff95b.png)

**Comment by Reyzerbit** [comment]
![image](https://user-images.githubusercontent.com/10405105/230467890-7c5824b9-08a0-4cd0-a2d8-d6b34a2dd5d9.png)
