### ISSUE TITLE
Bug: BURNER NOT PULLING PRICE

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#450]
![image](https://user-images.githubusercontent.com/114690243/230484976-5037230f-f390-4d64-baac-68f8b21eb763.png)

![image](https://user-images.githubusercontent.com/114690243/230485011-955d4520-f259-4b82-969e-4464e0a771e9.png)

**Comment by Reyzerbit** [comment]
Issue resides in outdated order pricing, please refresh.
