### ISSUE TITLE
Feature: Post Rewrite To-Dos

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#455]
We are working on a calculator for fuse fire feature and will need to talk through how this should look in ORE3D

**Comment by Reyzerbit** [comment]
Create a data middleman hosted on Core and updated daily for the initial pull of NS data on Ore3D load.

Add a checkbox to the launcher that allows the user to decided if they want to pull directly from NS (slow) or Data Warehouse (fast).

**Comment by Reyzerbit** [comment]
Rendering doesn't show color past 20000" of edging length (will be resolved with new 3D rendering system)

**Comment by Reyzerbit** [comment]
Can we develop the means for calculating fuel surcharge without saving, refreshing netsuite, opening estimate back up, adding fuel surcharge, save again....

I would need to see the Shipping cost, which is based on the order sub-total and Shipping Method.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/7e6a937d-a925-499b-b4b4-cc1e7e4fa9da)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/c145a8ab-7c88-4271-a943-cac1420b69f9)

**Comment by Reyzerbit** [comment]
This is probably a part of the code re-write, but we need to be able to generate a pdf of the estimates/so's to give to customers from Ore3D. NS has this functionality, but i've never researched if it can be accessed over API. check it out.

**Comment by Reyzerbit** [comment]
Can you have the Work Order(s) field on SO line items get a comma delineated list of the WO's generated for that line. This would include lines that only have a single WO as well. lmk if you have questions.

**Comment by Reyzerbit** [comment]
Merged into #455

**Comment by Reyzerbit** [comment]
Allow Rendering checkbox should remember setting.

It is resetting now. I can't tell what prompts it to do reset, if it's on-launch or when I run an update.

Either way I would prefer Ore3D to remember that setting. I can change it back in the event I want to re-enable rendering.

**Comment by Reyzerbit** [comment]
Make sandbox mode more visually unique to a user. My recommendation would be a custom-grayscale color theme, but i'm open to other suggestions.

**Comment by Reyzerbit** [comment]
Create a custom record in NS for Ore3D that stamps the Ore3D pricing data for that day as of 1201AM and Ore3D can reference to set pricing by timeline.

**Comment by Reyzerbit** [comment]
Button/checkbox to manually bypass Ore3D identifying something as standard.

Use cases:
instances when customization doesn't change dimensions or BOM
-Gap in skid
-Raised planting shelf
-etc

**Comment by Reyzerbit** [comment]
For admin users:

- CSV Export of proposal all BOMs and Routings
- Move this button under an 'Admin Feature' Tab -

It might make sense to wait until there are additional features. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/e307c3a4-8e40-41ad-9937-52709bc5bbbf)

**Comment by Reyzerbit** [comment]
Need a brainstorm session on how we can do this.

How difficult would it be to add a "FUSE" button to each standard fire feature we currently have? Most of our custom fire features are modifications to standard fire features.
Can the routings be unlocked to adjust times if needed?
Can we use the same math as the current fuse calculations?

**Comment by Reyzerbit** [comment]
Pre-Designed Items + Art Finishes
- DO NOT CHANGE TO 'MODIFIED'
- Remove price override
- let pricing flow through (minus CAD time) ***REQUIRES DISCUSSION WITH WSL***
--ALT: Allow finish BOM cost to add to pre-design override price.

**Comment by Reyzerbit** [comment]
**Issue:**
The misc. charge is adding quantity related to the child quantity. so an ignore build quantity button would help with this just like out BOM items. 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/f2587869-d906-4af3-899b-33fc6e010e32)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/b1ea76e6-7b99-4705-8d43-49316e21c331)

**Comment by Reyzerbit** [comment]
Admin feature: Force build to custom instead of predesigned.

**Comment by Reyzerbit** [comment]
Admin tools:
-Override labor margin.
-calc projected margin based on input price (I have an excel calculator that does this)
-override bom and labor rates
-other
