### ISSUE TITLE
Bug: Ore3D Slows Down after Adding 6-8 Fuse Children

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#458]
Bug doesn't happen every time, but when copying children in a fuse configuration ORE 3-D will crash quite a bit. While adding eight children, I experienced four crashes.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.6)
