### ISSUE TITLE
Feature: Remove character limit Max. for description field. 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#461]
The notes field doesn't offer nearly enough characters to properly qualify more complex items. Please remove character limit.

**Comment by Reyzerbit** [comment]
According to @mxidis this isn't possible, as Netsuite has a character limit of 999 characters. I'm going to assign this to him to see if he can change that somehow.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.6)
