### ISSUE TITLE
Feature: Split Curved Planters by Width

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#464]
Unable to split width of fuse curved planter. It automatically changes width to 1 piece but the rendering shows the split.

 
![image](https://user-images.githubusercontent.com/114690243/230951853-3e8c78d8-2ad4-4356-91af-544821d42c80.png)

**Comment by daniel11088** [comment]
still not splitting correctly. it reverts the width section to 1

<img width="850" alt="image" src="https://user-images.githubusercontent.com/114690243/231256270-db308866-0a2a-4b63-a398-8a6dc6d44bdd.png">

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.7](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.7)
