### ISSUE TITLE
Bug: FUSE EDGING IS PRICING AND CALCULATING MATERIAL AS PLANTERS

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#465]
![image](https://user-images.githubusercontent.com/114690243/230999277-c938cddc-08ed-4aa7-b36d-095c8a38687d.png)

![image](https://user-images.githubusercontent.com/114690243/230999351-c5a740fd-f59b-40ce-a754-51f2b20fabae.png)

**Comment by Reyzerbit** [comment]
Unable to replicate. It is possible i accidentally fixed this in 1.8.6. Once 1.8.6 is released, test this again and if issue, persists, let me know.

**Comment by daniel11088** [comment]
i updated to the newest version and the CAD time and curved fuse edging is not being calculated correctly

**Comment by Reyzerbit** [comment]
@daniel11088 I didn't know the issue resided in curved edging, not regular edging. Please specify curved edging vs straight edging next time, thanks! 😄

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.7](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.7)
