### ISSUE TITLE
Bug: Description Items Creating Duplicates

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#466]
Full crash on save with s1208 and a natural rust disclaimer. 

Was able to save without the disclaimer.

**Comment by Reyzerbit** [comment]
This bug appear to be caused by disclaimer items trying to duplicate themselves. I'm looking into a fix right now.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.6)
