### ISSUE TITLE
Bug: [Crash on New Proposal] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#47]
**Bug:**
New Proposal:
Allowed me to search for, and select a project. Crash at searching for customer.

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Unable to replicate. If no more information is given to replicate bug, bug will be closed in 7 days.
