### ISSUE TITLE
Feature: MAKING MODIFIED FIRE FEATURE OPTIONS THE SAME PROCESS AS PREFAB 

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#472]
![image](https://user-images.githubusercontent.com/114690243/231571134-f1e79f27-c5a7-4ca0-a40e-5ece11cd1a6d.png)

![image](https://user-images.githubusercontent.com/114690243/231571200-580783fe-e5ac-4497-bbc9-fc4891360599.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.9](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.9)
