### ISSUE TITLE
Bug: Math for Fuse Split Weight and Volume Preview is Incorrect

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#473]
![image](https://user-images.githubusercontent.com/114699058/231823271-2de1e8ef-1eee-426c-8899-a37cd0b4a05f.png)
ORE 3D Math for calculated weight and volume is incorrect

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.9](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.9)
