### ISSUE TITLE
Feature: CLEANING UP DESCRIPTIONS FOR CUSTOM COMPONENTS

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#476]
![image](https://user-images.githubusercontent.com/114690243/232123820-ad5ddbe6-13f7-4bfe-93df-94bc6a13ca79.png)

Can we get the O3DPLACEHOLDER removed form the description on custom components?
Why do question marks come up after the 90 and ft? Can those be removed?

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.9](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.9)
