### ISSUE TITLE
Bug: FABRICATED LIP BUTTON AUTOMATICALLY IS CLICKED WHEN FUSE CURVE PLANTER IS SPLIT

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#477]
Matt said this may already be a bug. Sorry if it's a duplicate

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.9](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.9)
