### ISSUE TITLE
Bug: [Edit Project Page Not Scrollable] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#48]
**Bug:**
On the Edit Project page> I clicked Return, but it has a pop-up that goes off the bottom of the screen. 

When I click off of the pop-up it goes away, but it won't let me 'Re-click' Return. It only gave me 1 opportunity before apparently 

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed with version [1.5.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.1)
