### ISSUE TITLE
WO Generation is changing line items to different items on SO's

### ISSUE THREAD

**Issue by mxidis** [Ore-Design/Ore-3D-Reports-Changelog#480]
S16316 completely changed line items when generating the WO.  you can see the original line item on proposal 42847.

**Comment by Reyzerbit** [comment]
Issue appears to be missing metal thickness value. Unable to replicate issue on my own, but best guess is thickness wasn't set properly.

**Comment by Reyzerbit** [comment]
Issue was most likely user error, as recreation seems unsuccessful. Reopen bug if issue persists.

**Comment by Reyzerbit** [comment]
I was wrong! Issue was thickness being auto-calculated for operations department clearance and below. Switched Lacey to Test User for now, long term fix in progress.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.9](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.9)
