### ISSUE TITLE
Bug: SELECTING CUSTOM REC CHANGES LIP DIMS AND REMOVES SKID

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#483]
If you select a custom rectangle the lips change from 1.5" to 1" and removes the skid. 

Can that be changed so lip and skids remain the same as our standard?

**Comment by daniel11088** [comment]
Let me run it by Matt and I’ll get back to you

**Comment by Reyzerbit** [comment]
Closing as expired. If the issue pops back up, feel free to re-open the report 😄
