### ISSUE TITLE
Bug: [Proposal Contact Not Constrained to Customer] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#49]
**Bug:**
Proposal contact allows for ANY contact from ANY customer. This should be constrained to existing contacts assigned to the Customer that is selected. 

Contact list is not alphabetical. Can it be?

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed with [Update 1.5.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.2)
