### ISSUE TITLE
Feature: DESCRIPTION CONSISTENCY

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#493]
Would it be possible to have the descriptions uniformed so we don't have to manually change when we have a mix of Fuse Planters and regular planters?

![image](https://user-images.githubusercontent.com/114690243/234087870-15372632-adcd-4a33-b4a1-8b393f37a9bc.png)

**Comment by daniel11088** [comment]
Lets the descriptions always show reveal even if it is 0" like with the Fuse descriptions


[Ore Logo]
Daniel Herring
Project Coordinator

***@***.******@***.***>
→

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>



________________________________

**Comment by Reyzerbit** [comment]
Is this the general agreement from the estimating department? Im a little confused what your response was supposed to mean, sorry! 😅

**Comment by daniel11088** [comment]
Yeah


[Ore Logo]
Daniel Herring
Project Coordinator

***@***.******@***.***>
→

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>



________________________________

**Comment by Reyzerbit** [comment]
Implemented/released in [Version 1.8.12](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.12)

**Comment by daniel11088** [comment]
looks like this isn't updating properly in netsuite. The descriptions are still different.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/5707ecf7-1f10-43ed-a322-bdc3f2801cf5)

**Comment by Reyzerbit** [comment]
Continuing issue stemmed from improper catalog data. Will be fixed in 1.8.14.
