### ISSUE TITLE
Bug: [Fuse Model] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#50]
**Bug:**
After splitting the model view places multiple children on top of each other. 

No way to select by

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed/Implemented in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
