### ISSUE TITLE
Bug: Pricing UI Not Updating Properly On Load

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#501]
when a new order is opened, the subtotal and pricing date have all 7s listed. I just want to make sure that pricing is being updated correctly.

![image](https://user-images.githubusercontent.com/114690243/234643986-64313d13-59e4-4c82-92c9-77c3211dba90.png)

**Comment by Reyzerbit** [comment]
Implemented/released in [Version 1.8.12](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.12)
