### ISSUE TITLE
Bug: Splitting a fuse planter changes the reveal back to 0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#514]
![image](https://user-images.githubusercontent.com/114690243/234960277-656e0703-931e-49ff-8979-5964b29bcb13.png)

![image](https://user-images.githubusercontent.com/114690243/234960563-f743ecec-9bef-4893-bd9d-94cac4d51931.png)

**Comment by Reyzerbit** [comment]
Implemented/released in [Version 1.8.12](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.12)
