### ISSUE TITLE
Bug: [Volume Calcs Incorrect] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#52]
**Bug:**
Cubic Foot calculator on 'parent' should be driven by child section dimensions & qty, not description dimensions.

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
I have received multiple complaints about auto-calculating fuse parent elements by child info. Unless I receive a request for this change as unanimous request from entire department, implementation will not continue.
