### ISSUE TITLE
Bug: Curved Fuse Planter looks to not be calculating correctly. 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#520]
**Recreate:**
1. Add fuse curved planter section. 
2. See that Routings look incorrect.

**Comment by Reyzerbit** [comment]
Hey Josh!
When you say "routings look incorrect", are you referring to the fab time not going up?

**Comment by Reyzerbit** [comment]
Talked to Josh in person: Issue seems to be that finishing is way too high, and Fab and Prefab times don't seem to change at all.
Going to look into this and see what's up. Possible missing Specs issue.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.13](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.13)
