### ISSUE TITLE
Feature: Option to see planter dimensions in left panel for quick review 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#522]
![image](https://user-images.githubusercontent.com/114424580/236229979-ce95d9e6-71f3-44e9-974b-3facf0b500ae.png)
![image](https://user-images.githubusercontent.com/114424580/236230558-503c1ada-e8ab-4e9f-822f-131072972505.png)

**Comment by Reyzerbit** [comment]
Hey Josh!
This feature actually already exists!
1. Select the magnifying glass icon (see pictured)
![image](https://user-images.githubusercontent.com/10405105/236243384-1daf80da-169f-450b-9def-e15e4ca84413.png)
2. In the drop down that appears, select 'Dimensions'
![image](https://user-images.githubusercontent.com/10405105/236243864-d7d56f1f-5326-4b05-8554-8567289197b0.png)
3. All the of the build tabs will then be populated with a "Dimension" field for preview.
![image](https://user-images.githubusercontent.com/10405105/236244180-976d47a4-8210-4111-b933-f2518354c6c5.png)

Hope this helps! 😄
