### ISSUE TITLE
Feature: New Proposal Format is Confusing Customers

### ISSUE THREAD

**Issue by connergeoff** [Ore-Design/Ore-3D-Reports-Changelog#523]
**Issue:**
Customers do not understand our new proposals, specifically as it pertains to anything Fuse.  They do not understand why 2 qty columns, FS qty and then Qty, as well as which one the weight would be associated with.

**Solution:**
Reduce to one Qty column w/out FS mentioned - customer does not need to know parent, child, etc... and if it's a standard item, it won't be FS.

**Additional Context/Questions:**
This is confusing to older customers and new customers alike - multiple calls/emails a week since it changed.

**Comment by Reyzerbit** [comment]
Hey @connergeoff!
This is a Netsuite forms thing that I personally don't have control over. I'm handing this off to @mxidis so he can take care of this.
Thanks! We'll get this resolved ASAP 😄

**Comment by mxidis** [comment]
Updated the printed forms
