### ISSUE TITLE
Bug: [Add Standalone Item - Add Other - Duplication Issue] [Ore3D Version (1.8.12]

### ISSUE THREAD

**Issue by ohicks** [Ore-Design/Ore-3D-Reports-Changelog#525]
**Bug:**
The "other items" of fuel surcharge and 500-1000 options now duplicate each time I go into this section. It goes from 2 "other" options to 4 to 6 to 8, etc. the more times I go in and out of the "other items" section - whether within the same proposal or going in and out of other proposals. It only resets to 2 "other items" if I close out and reopen Ore3D altogether. 

**Recreate:**
1. Load any proposal (ex: 43224)
2. Click on "Add Standalone Item"
3. Click on "Add Other"
4. See two options (500-1000 and Fuel Surcharge)
5. Add Fuel Surcharge
6. Go back to "Add Standalone Item" --> "Add Other"
7. See now that there are four options instead of just two, two of 500-1000 and two of "Fuel Surcharge
8. Go back out and into this "Add Other" section and it will have added again, with 6 options now
9. This will continue as you go back in and out of the "Add Other" Section 

**Expected Behavior:**
There should only be the two options in the "Add Other" section 

**Additional Context/Questions:**
![Screenshot 2023-05-04 at 9 50 08 AM](https://user-images.githubusercontent.com/132599114/236271424-75fee56b-9cca-4202-b29d-9b61af3149e4.png)
![Screenshot 2023-05-04 at 9 50 26 AM](https://user-images.githubusercontent.com/132599114/236271428-566f45fa-379d-4151-9900-1e59c7b823fc.png)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Version 1.8.13](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.13)
