### ISSUE TITLE
Bug: Saving a copied proposal replaced planters on original

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#534]
•	MI created a copy of 43051.
•	43275 created.
•	Added new planters to 43275. Saved and closed.
•	Opened 43051 after saving/closing 43275 to find that the planters saved in 43275 took the place of the top 2 planters on 43051.

**Comment by Reyzerbit** [comment]
Me and @mxidis ran multiple attempts to recreate this issue to no avail. We are going to keep our eye out for a little bit, but so far we can't seem to reproduce the error.
Please let us know if it happens again! 😄
