### ISSUE TITLE
Feature: Conversation about adding components to fuse planters/edging

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#535]
Can we have a conversation about the how components, lights, bench brackets, etc., get added to fuse sections? The current set up requires us to make calculation outside of ORE3D before entering them.

**Comment by daniel11088** [comment]
Matt said that you, Jake and him met about it on Friday so I think you can close this out unless you still had questions about it

**Comment by Reyzerbit** [comment]
Sounds good!

Merged into #553
