### ISSUE TITLE
Feature: We need a Cursor

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#536]
It's extremely frustrating to not have a cursor on the screen and to not know when we are able to type in a field. This would probably save a significant amount of time just from the time wasted on useless typing.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.8.14](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.14)
