### ISSUE TITLE
Bug: Save auto-recovery deletes notes when used 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#537]
**Recreate:**
1. Add notes
2. Crash ORE-3D 
3. Select autosave to recover 
4. Notes will be erased

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.8.14](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.14)
