### ISSUE TITLE
Bug: [Messages Overlap] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#54]
**Bug:**
With multiple messages, specifically section length, the messages will overlap with the message under it

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed with version [1.5.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.1)
