### ISSUE TITLE
Bug: Exit Add standalone item menu [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#541]
**Bug:**
Can't exit the add standalone item menu without adding an item. 

**Recreate:**
1. Load any order 
2. Click on add standalone item/ white box with plus inside at bottom of subtotal box
3. Try to exit menu without adding item
4. no error message

**Expected Behavior:**
Have an option to hit escape or have a UI option to exit menu

**Additional Context/Questions:**
Only way we have found to exit menu is to add an item and then delete the item after if we didn't need to add an item.

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.8.14](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.8.14)
