### ISSUE TITLE
Bug: Granite top for fireplace [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#548]
**Bug:**
adding granite top for fireplace in child loads it at $0.00

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/fcb88c69-bf90-4bbe-be29-6a7422a0be92)

**Comment by Reyzerbit** [comment]
I'll talk to you about this, but not a bug 😄
