### ISSUE TITLE
Bug: All BOM options being pulled for Predesigned A4023: Fire Bowl 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#554]
Not sure if this is intentional but it does look a like bug. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/e90adaef-9f91-473a-b581-452bd8872e9c)

**Comment by Reyzerbit** [comment]
We actually just refreshed this, please restart your client 😄
