### ISSUE TITLE
Feature: Catalog Auto-Detect location

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#560]
Move this button under an 'Admin Feature' Tab -

It might make sense to wait until there are additional features. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/e307c3a4-8e40-41ad-9937-52709bc5bbbf)

**Comment by Reyzerbit** [comment]
Merged into #561
