### ISSUE TITLE
Feature: Admin Features

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#561]
For admin users:

- CSV Export of proposal all BOMs and Routings
- Move this button under an 'Admin Feature' Tab -

It might make sense to wait until there are additional features. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/e307c3a4-8e40-41ad-9937-52709bc5bbbf)

**Comment by Reyzerbit** [comment]
Merged into #455
