### ISSUE TITLE
Bug: "Total Price" Field on BOM Component Lines is Wrong

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#574]
**Bug:**
Line item price is very different from subtotal 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/0f346848-9186-41bb-a3fb-73057772134e)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.9.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.9.1)
