### ISSUE TITLE
Bug: Fuse parent additional quantities 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#575]
**Bug:**
CAD should be removed from additional parent quantities. 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/bd43fdd6-91df-468d-b544-ac8415813e39)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/df46c9f0-ebd9-4a69-b0ce-7d31e18f39fb)

**Comment by Reyzerbit** [comment]
Merged into #578
