### ISSUE TITLE
CAD time in Fuse

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#578]
**Bug:**
CAD time is being split by total items in the parent quantity. Price of child and single parent item is not reflected by change of CAD Time
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/8748635b-3dd4-4a73-9a79-980665e97b1e)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/41fc74da-f04e-4abc-80b5-ae11f6cc1afd)

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.9.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.9.1)
