### ISSUE TITLE
Proposal Copy Function - Build Record references

### ISSUE THREAD

**Issue by mxidis** [Ore-Design/Ore-3D-Reports-Changelog#579]
The copy proposal function doesn't generate new Ore3D Build records for the line items that reference them.  This leads to data from a copied proposal updating the build data on the proposals it was copied from

**Comment by Reyzerbit** [comment]
Fixed/implemented in [Release 1.9.1](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.9.1)
