### ISSUE TITLE
Bug: ROUTING & BOM NOTES

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#584]
[BOM & Routing Notes.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/11627719/BOM.Routing.Notes.pdf)

**Some math errors have been resolved**

- Reformat BOM section to mirror Routings
- Remove pricing summary at bottom of receipts page
- add totals under cost and price columns of routings & BOMs
- Adjust functionality & name of "Display per Unit"
- *** BUGS IN MATH FUNCTIONS **** (SEE NOTES)
- Admin able edit margin rates
- Pricing era drop down to historical dates
- Update Misc Charges to mirror Special Order Component (see notes)

**Comment by Reyzerbit** [comment]
Split UI reformatting into Feature Request #589
