### ISSUE TITLE
Bug: Fuse parent not discounting CAD on quantities

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#593]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/9c68faab-23d1-4c74-840a-b37c6f263614)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/c890443c-d61c-492e-b783-4a76eee942e8)

**Comment by Reyzerbit** [comment]
Discussion with Matt Israel decided to remove this functionality altogether until a later decision is made. Ask Matt for further questions.
