### ISSUE TITLE
Bug: Ore3D taking up 98% of RAM [Ore3D Version (1.9.1 etc)]

### ISSUE THREAD

**Issue by MattRamsaur** [Ore-Design/Ore-3D-Reports-Changelog#596]
Ore3D is chocking out my work computer by taking up 98% of system memory. IS there a plan to make this more memory efficient or is sales just getting better computers? This is causing 3-5 second delays on every single thing I type or click on every application.

![Screenshot 2023-06-06 123249](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/135739024/a1af7d17-07b5-4d1f-a122-6e5d53f2d325)

**Comment by Reyzerbit** [comment]
Ended up making a temporary fix by getting Ramsaur a desktop. This problem will be permanently fixed once the rewrite is done
