### ISSUE TITLE
Bug: [Copy function crashed Ore3D & did not create clone] [Ore3D Version (1.9.1)]

### ISSUE THREAD

**Issue by ohicks** [Ore-Design/Ore-3D-Reports-Changelog#603]
**Bug:**
I created a copy of 43011 in Ore3D and chose to create this as a clone - however when it was saving the copy, it not only crashed Ore3D but also did not clone anything. It only created a blank proposal #43748. It did not copy over the correct shipping info on new proposal, either. 

**Recreate:**
Not sure how to recreate, can only explain what happened. 

**Expected Behavior:**
Chose to create a clone of #43011 with the copy function in Ore3D - but only got a blank copy. It did not copy over any shipping info, did not keep the same PC assigned, or any estimating notes, either. A true "blank" copy which is not helpful. 

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Merged into #594
