### ISSUE TITLE
Bug: Ore3D Price OVERRIDING 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#607]
S16610
*I overrode item pricing so the discount would function. 

-Ore3D Price override doesn't stay checked. (can you put this above the 'Ore3D Pricing Data' field?)
-Overriden Ore3D price doesn't push into NetSuite

**Comment by Reyzerbit** [comment]
At some point this got fixed and I just never closed this.
