### ISSUE TITLE
Bug: PLACEHOLDER - Pre-Designed Items + Art finishes

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#608]
Pre-Designed Items + Art Finishes
- DO NOT CHANGE TO 'MODIFIED'
- Remove price override
- let pricing flow through (minus CAD time) ***REQUIRES DISCUSSION WITH WSL***
--ALT: Allow finish BOM cost to add to pre-design override price.

**Comment by Reyzerbit** [comment]
@MattIsrael Any updates on this?

**Comment by Reyzerbit** [comment]
Merged into #455

**Comment by daniel11088** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/d07e9c33-1986-4bed-b4c3-712cf7779b74)

**Comment by daniel11088** [comment]
No action items for this bug at this time.
Israel to meet with Shane and Jared to establish pricing
