### ISSUE TITLE
Pricing Conflict: Firepit Lids on Pre-Designed

### ISSUE THREAD

**Issue by ohicks** [Ore-Design/Ore-3D-Reports-Changelog#611]
**Bug:**
The price of a pre-designed firepit raised lid has 52% margin added onto it in Ore3D while the regular (not raised) lid is correctly priced. These should be the same price; we have not previously had a price difference between the two options on pre-designed firepits. Looks like the margin # just needs to be taken out to resolve. Have noticed this for the 4013, 4023 and 4019 so far but imagine that it extends to other pre-designed models.

**Comment by jdrake89** [comment]
These have been reviewed and changed per the list and current pricing set.
