### ISSUE TITLE
Bug: Component Search Box Version 1.9.2

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#617]
**Bug:**
Search bar display isn't displaying as expected. Typing to find item is not narrowing down list. list is not filtering
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/eefedddf-1724-4742-9548-b827850bc317)

**Comment by Reyzerbit** [comment]
Note for Jacob: Add check for each searchable field to check if string is null AND if string is empty
