### ISSUE TITLE
Bug: A3008 (single & double) enters as Modified. 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#619]
When the single and double A3008 are added Ore3D pulls them in as Modified

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/abc9518a-2743-4b1d-9fb1-f103d29f8e89)

**Comment by Reyzerbit** [comment]
This is because there is no pre-designed pricing for 3008s. In order to resolve this issue, I need to know how much this product costs without the benches attached. Is that information you have @MattIsrael ?

**Comment by MattIsrael** [comment]
Have = no
responsible for = yes

I have 1 question for finance, then I can get you that info.

**Comment by Reyzerbit** [comment]
@MattIsrael any update on this?

**Comment by Reyzerbit** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/10405105/8a41aeac-5c01-4bb5-b2d9-06e43651f5c8)
