### ISSUE TITLE
Bug: Description Quantity Issues

### ISSUE THREAD

**Issue by connergeoff** [Ore-Design/Ore-3D-Reports-Changelog#626]
**Bug:**
Issue between Ore3d and Netsuite. In description column, components showing as quantities of 2 when should be 1.  Shows correct component quantities in Ore3D.

![Screenshot 2023-06-15 at 8 11 33 AM](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/132588288/c0762949-c2ca-4853-88c2-0a7833c6f873)

**Comment by Reyzerbit** [comment]
@mxidis issues a temporary fix for this until we can further discuss this in a meeting.
