### ISSUE TITLE
Copying a large proposal didn't bring over all the data?

### ISSUE THREAD

**Issue by mxidis** [Ore-Design/Ore-3D-Reports-Changelog#631]
Geoff just had a bug during a copy through Ore3D that was kinda strange. Large custom estimate, all of the custom items copied fine. The last line was a pre-designed fire pit and when it copied it only put the price of the body (not accessories) into the NetSuite price. When I opened Ore3D the fire pit had the full price that it should. I resaved the proposal in Ore3D and refreshed NetSuite and the pricing updated to be correct.

43876/43906

906 is updated now, but the line history should have recorded what I did

**Comment by Reyzerbit** [comment]
@mxidis was unable to replicate, deemed unable to replicate.
