### ISSUE TITLE
Feature: Fuel Surcharge Process

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#643]
Can we develop the means for calculating fuel surcharge without saving, refreshing netsuite, opening estimate back up, adding fuel surcharge, save again....

I would need to see the Shipping cost, which is based on the order sub-total and Shipping Method.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/7e6a937d-a925-499b-b4b4-cc1e7e4fa9da)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/c145a8ab-7c88-4271-a943-cac1420b69f9)

**Comment by Reyzerbit** [comment]
Merged into #455
