### ISSUE TITLE
No Drain Hole in Description For Edging

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#645]
Get rid of Display of drain holes in description of parent in fuse edging. There isn't  an option for drain holes in edging and it should reflect in the description.  
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/f6d87e21-6953-4bb1-9787-d389f4e97529)

**Comment by Reyzerbit** [comment]
This request directly conflicts with previous request #604. We're going talk about this request during the next Ore3D training meeting and get a definitive answer.

**Comment by CBarsell** [comment]
Bug #604 is in reference to Fuse Planters not Fuse Edging. Please Process Bug #645 That relates to Fuse Edging only.

Thanks!
