### ISSUE TITLE
Bug: [Fuse Lip Depth] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#65]
**Bug:**
Fuse Lip Depth won't set to 0. 

Is this because of a stiffening bar??? if so, we might want to make an adjustment on how this presents, if it's even visible. 

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Intentional feature. Feel free to talk to me/schedule meeting about possible alternatives.
