### ISSUE TITLE
Bug: SALES REP NOT BEING COPIED WHEN ORDER IS COPIED IN ORE3D

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#655]
I made of copy of 44145 and the sales rep was not copied. The copied order is 44185.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/8a62f001-0b52-4537-8149-05a370c5d5f5)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b35a4d4d-0923-4e88-8b46-fb8a69d69050)

**Comment by daniel11088** [comment]
It did it again and Geoff mentioned it happened to him this morning. Any chance this could get repaired with the next update?
 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/74ed0160-57af-4dce-8841-43eed807c998)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/14cc683c-6a33-4155-8308-43f10b46fa99)

**Comment by Reyzerbit** [comment]
Already in progress, we'll have it in by 1.9.7 😄
