### ISSUE TITLE
Bug: Abstract Item Nuked [Ore3D Version 1.9.5]

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#656]
**Bug:**
For Proposal 44204 I had made an abstract item for a post and saved it to netsuite. I went back to modify the proposal and there is nothing in Ore3D anymore. Netsuite is still saying the item is there in the proposal. I then went to the Autosave log and found the item and all my notes with it but when I hit the save button it crashes Ore3D before it finishes the save cycle

**Comment by Reyzerbit** [comment]
Unable to get ahold of the autosave data so unable to replicate. If this happens again, get ahold of me immediately so I can grab the autosave data for testing. Sorry! 😅
