### ISSUE TITLE
Bug: Parent Level Routings Are Editable

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#657]
-BOM edits at parent level don't change price (correct behavior), but the option to add anything through the UI is misleading. Disable the UI to prevent adjustments to parent level.
(Edited by JRB for clarity)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/decaf888-9eb6-4304-b274-0fbed5525635)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/b9fb5608-0127-4bb2-a06b-9d600cbaf064)

**Comment by Reyzerbit** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/10405105/8d281cfe-24fd-43fd-b195-a52b48aec19b)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/10405105/04c0d731-73ce-4f12-bfdd-efa3cb0652db)
