### ISSUE TITLE
Feature: [Enhance Notes Area]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#66]
In the Notes tab it would be helpful to see the description as it will print into NetSuite. Maybe this is above the Customer Notes field? 

We would use this to check formatting, ensure max dimensions are correct, ensure all options are present...

**Comment by Reyzerbit** [comment]
Fixed/Implemented in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
