### ISSUE TITLE
FUSE FIRE FEATURE CONVERSATION

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#669]
Need a brainstorm session on how we can do this.

- How difficult would it be to add a "FUSE" button to each standard fire feature we currently have? Most of our custom fire features are modifications to standard fire features. 
- Can the routings be unlocked to adjust times if needed? 
- Can we use the same math as the current fuse calculations?

**Comment by daniel11088** [comment]
we also need to adjust pan dims to accommodate multiple burners. Currently pan dims are locked and match burner dims.

**Comment by Reyzerbit** [comment]
Merged into #455
