### ISSUE TITLE
Feature: [Reorder Fuse Rt. Panel]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#67]
**Issue:**
Some highly used fields (material gauge) are at the bottom of the list.

**Solution:**
If we group the most commonly used/edited fields at top of this panel the more rarely used stuff can bleed off the bottom.

Field Titles in Proposed Order:
1. Dimensions
2. Material
3. Finish
4. *Details (new field)
- Drain Holes y/n
- Lip Width*
- Reveal Type
- Reveal Height

5. *Misc (Or consider hiding all of this - it would be RARELY used if ever)
- Reveal L&W inset
- Lip Depth
- Gusset inputs
- Fuse End Height

**Alternatives:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed with [Update 1.5.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.2)
