### ISSUE TITLE
Feature: [10.27 UI Comments]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#68]
[10272022.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/9883231/10272022.pdf)

See attached PDF for UI comments/thoughts relating to Fuse and the left [summary] panel.

Get with me if you can't read my writing or you'd like me to expand on any of these notes.

**Comment by Reyzerbit** [comment]
[Responses.pdf](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/9913430/Responses.pdf)

**Comment by Reyzerbit** [comment]
Fixed with [Update 1.5.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.2)
