### ISSUE TITLE
Bug: Glass Surround Pricing Inaccuracy

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#681]
**Bug:**
Pricing looks too low.
The old pricing sheet says it should be $2,820 for round glass at 24"D

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/ab786d33-e45d-4e9b-9dec-36c5c0e61763)

**Comment by Reyzerbit** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/10405105/9c3d3628-70b0-4f98-9cd2-df17cd7ef261)

Discussed issue, problem is resolved with different process. Closing.
