### ISSUE TITLE
Feature: Ignore Build Quantity Button For Misc Charges

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#686]
**Issue:**
The misc. charge is adding quantity related to the child quantity. so an ignore build quantity button would help with this just like out BOM items. 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/f2587869-d906-4af3-899b-33fc6e010e32)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/b1ea76e6-7b99-4705-8d43-49316e21c331)

**Comment by Reyzerbit** [comment]
Merged into #455
