### ISSUE TITLE
Reverting split fuse deletes add-ons

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#687]
Reverting FUSE build splits deletes add-on components and sometimes reverts color to TBD

**Comment by Reyzerbit** [comment]
After all my own testing, I can't seem to recreate the issue on my end. I think it may be an isolated incident to a very specific case. Hopefully the rewrite will fix most of these issues.

**Comment by daniel11088** [comment]
Chris and I both replicated this again. Can you come over and make sure we are doing this properly
