### ISSUE TITLE
Feature: [BOM Placeholder Item (Not In NetSuite)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#69]
**Issue:**
Estimating often needs to include pricing for items that are not in NetSuite.
-3rd party electrical switches/outlets
-New fire pit burners

**Solution:**
Ability to add something akin to a Custom Component (experlogix), but would create a BOM placeholder. The current Custom Component field in experlogix doesn't get pushed to the BOM so there is a large opportunity for Supply Chain to miss something we enter.

**Alternatives:**
Open to other ideas. Supply Chain and Estimating would be the stakeholders of this.

**Comment by Reyzerbit** [comment]
Closed as duplicate of #61
