### ISSUE TITLE
Bug: Fuse Curve Split Issue

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#697]
**Bug:**
I have a large fuse curve section that needs to be split by width and length. I select split sizes that will make it fit on one sheet and then it splits into separate children with different sizes than the fuse split size was supposed to be.
Before Splitting:
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/adc1541f-9121-4f93-9373-91481fea726b)
After splitting:
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/72c87c26-d429-4e37-9c3e-a439ba5a555d)

**Comment by MattIsrael** [comment]
Batista - Can you please copy all the splitting 'logic' & defaults from straight fuse to curved fuse?

The only difference should be that 'fabricated lips' should default to true (if there is a lip). I believe all that logic is accurate.
