### ISSUE TITLE
Feature: Proposal Disclaimers

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#70]
1-Automated disclaimers (only 1 instance of the disclaimer/proposal. Always at the bottom.):
examples:
-Natural Rust = Rust Disclaimer
-Oxidized Zinc = Ox. Zinc Disclaimer
-Custom= Shop Drawings Disclaimer

2-Ability to add Proposal Note - essentially this is a line item with no cost where we can type any notes that wouldn't live within a specific line item. Typically applying to the entire proposal.

**Comment by Reyzerbit** [comment]
Closed as duplicate of #129
