### ISSUE TITLE
Feature: Testing Features

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#701]
Need ability to change all values. Doesn't need to be in the live production system, it could be in the sandbox or somewhere else where there is no opportunity for mis-use. Could be tied to mgr role too. 

I can create a list of features if this is something y'all are willing to work on in the future?

-Override labor margin.
-calc projected margin based on input price (I have an excel calculator that does this)
-override bom and labor rates
-other

**Comment by Reyzerbit** [comment]
Moved to rewrite feature request #455
