### ISSUE TITLE
Calculated weight is not adding from material sqft

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#705]
Where is the calculated weight coming from?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/2f4b3dfa-6acb-4118-8847-6bc15f004544)

**Comment by Reyzerbit** [comment]
Build weight is calculated by the size of the build, not BOMs. Making BOM drive weight would require more data to be pulled from Netsuite, and would mean that BOMs would have to be calculated BEFORE everything else, which, with the current code base, is not possible.

If you feel that the amount of metal used in a product is wrong, and there needs to be more/less, let's setup a meeting to talk math so we can get the BOMs calculating correctly.
