### ISSUE TITLE
Ignore Build Quantity button removes item from overall price

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#706]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/7560f216-f356-497d-a47e-ec07eeb73dca)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/bf2156b8-7b8c-4b27-b506-738511da821d)

**Comment by Reyzerbit** [comment]
Talked to Daniel about it, is behaving as expected
