### ISSUE TITLE
Bug: Custom capsule shape code not recognizing NetSuite bowls  

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#716]
Custom capsule shape code is not recognizing NetSuite bowl diameter. 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/3f605a7d-ddc9-4a55-8b16-2497349b760e)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/3ce18f7b-0498-4a80-8fb1-041b3deba78d)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/cbf09f3a-fd1e-45ce-a592-cbdca14061e3)

**Comment by Reyzerbit** [comment]
Talked to Josh, issue was mismatching bowl dimensions. Now resolved.
