### ISSUE TITLE
Bug: Description Contains Overlapping Text

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#718]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/4c15ec00-9ef6-4f29-bd3d-2e2e145eb748)

**Comment by Reyzerbit** [comment]
This is an issue caused by invalid text formatting. Somewhere in the description, invalid characters have been copied/pasted. If you send me the proposal number I can fix it, but other than formatting the text properly, there is no way around this.
