### ISSUE TITLE
Bug: BOM Items deleted after reverting Fuse split, and special order items being unusable after it gets deleted

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#724]
**Bug:**
After adding BOM items to a child, if I revert the split to do different section lengths it will delete all of my BOM items. 
This causes issues if we make a special order item. we can't add back special order items we've created and we can't make the items again because the name already exists.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/ba41083b-d840-4760-914b-8073ff7f9a6d)
After reverting.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/4d74b65a-3e28-4fa8-911b-0ffdd1f06b85)
After trying to add back a special order item
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/0a263818-5a07-448a-b828-45a8de4257f0)

**Comment by Reyzerbit** [comment]
Talked to Chris about this, issue can be fixed by reloading database. Once the rewrite is done, issue should be resolved.
