### ISSUE TITLE
Remove "reveal" option on curved edging to match straight edging

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#726]
Can we get rid of reveal height option for curved edging?

It needs to match straight edging.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1c114bc7-2616-40f0-a240-9e2e756947b5)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/65662439-6ab4-45fd-a998-b69c2ed2cde1)

**Comment by daniel11088** [comment]
Can we also add "straight" fuse edging to the description? When we have a mix of straight and curved in a parent, the description reads as only being curved edging. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b6c4dfb2-f38c-45e9-909a-29d7eccb28b8)

**Comment by Reyzerbit** [comment]
Merged into #759
