### ISSUE TITLE
Couple requested changes 

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#732]
Can "custom" designs keep standard lip/skirt/skid profile?
IE: 1108/09/10 all have 1.5" lip with 1" skid but when you select custom it changes to 1" lip with no skid.
 
Custom Cove Pomo changes description to "Modified Rec". Can it be changed to "Modified Cove Pomo"

**Comment by daniel11088** [comment]
Custom Round Taper changes to Modified Cone.
Custom Silo changes to modified cylinder planter.

**Comment by Reyzerbit** [comment]
Merged into #759
