### ISSUE TITLE
Can we get the skid description to be the same for all configurations?

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#742]
Remove the "height" from the modified rec description.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/dc505e72-9da2-4fd0-8b20-ef85c9632fc5)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/94ca5c86-907f-466c-a219-b08ce71f6850)

**Comment by Reyzerbit** [comment]
Resolved in rewrite. Merged into #759
