### ISSUE TITLE
FINAL STEPS FOR REWRITE

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/Ore-3D-Reports-Changelog#746]
Final features to make 2.0 on par with 1.0:

- Pre-designed detection ✅ 
- Open in Netsuite ✅ 
- Refresh Pricing ✅ 
- Tag sorting/improvements ✅ 
- Clone orders ✅ 
- Description calculation/displaying✅ 
- Popout text box specs✅ 
- Spec linking ✅ 
- Work order generation ✅ (Still need to do extensive testing on non-advanced BOMs mode)
- Child build BOM/Routing stacking in receipts panel ✅ 
- Build tile is catalog and has work order flag ✅ 
- Customize catalog from netsuite data ✅ 
- Labor/material estimation per shape code ✅ 
- Dropdown option filtering ✅ 
- Misc charges ✅
- Edit stored values in routings, bom, misc, and transaction ✅

High Priority Items:
- Plugin management ✅ 
- Save version tag ✅ 
- Log cleaning ✅ 
- Prevent child from work order generation if parent (of any distance) already has work order ✅ 

Things that should be easy to do:
- Lock orders on expired ✅ 
- Improve work order selection UI ✅

**Comment by mxidis** [comment]
Labor/material estimation per shape code
