### ISSUE TITLE
Bug: [Routings not changing cost] [Ore3D Version (1.5.2)]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#75]
**Bug:**
Overriding routings of standard products/customs based on shape will not change the cost of the product. 

**Recreate:**
1. Load order '#40147'
2. Click on 'Line Item 3'
3.  Switch to receipt and update routings.
4. See price not changing 

**Expected Behavior:**
Price to change when routings are overridden.

**Comment by Reyzerbit** [comment]
Implemented/fixed with version [1.5.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.3)
