### ISSUE TITLE
Feature: SO Price Override 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#753]
#1: Pop-up dialog box references 'new' / 'old' and 'override' / 'don't override' - Please match language. Showing $ values for each option would be even better. 

#2: Resolve unit price in 'override' scenario. Math function is not true:

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/4713dd60-b58d-4fb8-835c-4de3076cee47)

**Comment by Reyzerbit** [comment]
To be resolved in rewrite.
