### ISSUE TITLE
Pre split dims

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#758]
Would it be possible to show pre-split dims on fuse children?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/7e0bf35b-1b88-4df0-9e2d-497fc9dab808)

**Comment by Reyzerbit** [comment]
This is going to be resolved with the rewrite, as Fuse is going to fundamentally change.
