### ISSUE TITLE
Bug: [Unable to cancel creation of special order component ] [Ore3D Version (1.5.2)]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#77]
**Bug:**
Unable to cancel creation of special order component without closing out of ORE-3D

**Recreate:**
1 Load order: 40148
2. Click on Receipt tab. 
3. Click on "Create Special Order Component" button. 
4. Try to exit screen without closing ORE-3D or completing creation of special order component 

**Expected Behavior:**
An option to cancel creation of special order component

**Comment by Reyzerbit** [comment]
Implemented/fixed with version [1.5.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.3)
