### ISSUE TITLE
Other: [ 1208 - You - Product material check]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#78]
Confirm that the material gauge for the You is correct. The shop drawings call for it to be 1/8" AL. ORE-3D has item as .090.

**Comment by Reyzerbit** [comment]
Implemented/fixed with version [1.5.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.3)
