### ISSUE TITLE
Crash with capsul

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#785]
[FAILED_LOADS.txt](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/13844871/FAILED_LOADS.txt)

[GITHUB_ERR.log](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/13844873/GITHUB_ERR.log)

[Ore3D Log 01-05-2024 10.16.15.log](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/13844875/Ore3D.Log.01-05-2024.10.16.15.log)

[Ore3D Log 01-05-2024 10.18.11.log](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/13844877/Ore3D.Log.01-05-2024.10.18.11.log)

**Comment by daniel11088** [comment]
[Ore3D Log 01-05-2024 10.23.51.log](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/13844881/Ore3D.Log.01-05-2024.10.23.51.log)
[Ore3D Log 01-05-2024 10.29.19.log](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/files/13844883/Ore3D.Log.01-05-2024.10.29.19.log)

**Comment by Reyzerbit** [comment]
Talked to Daniel, problem resolved in person
