### ISSUE TITLE
Bug: Sleeves Not Available

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#79]
**Bug:**
No option to add/search for irrigation sleeves. 

**Recreate:**
1. Load order: 40148
2. Click on receipt tab. 
3. Click "Select a component" button. 
4. Search irrigation sleeve or electrical sleeve 

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Working with Mike and Jake Drake to add sleeves to Ore3D

**Comment by Reyzerbit** [comment]
Fixed/implemented with [Version 1.5.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.6)
