### ISSUE TITLE
Bug: [Parent calculator adding additional add-on components ] [Ore3D Version (1.5.2)]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#80]
**Bug:**
Parent bill of materials add-on option quantity increases by number original quantity every time parent is clicked. 

**Recreate:**
1. Load order: 40149
2. Click on Fuse planter A 
3. Click receipt tab
4. Click parent 
5. See quantity increase

**Expected Behavior:**
No changes to quantity of add-on options. 
**Additional Context/Questions:**
Only happens when add-on option is added to the child not the parent.

**Comment by Reyzerbit** [comment]
Implemented/fixed with version [1.5.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.3)
