### ISSUE TITLE
Pricing and routings discrepancy between new and old ORE3D

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#800]
Pricing and routing are more in the new ORE3D.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/dc9e3a86-47cb-4a9f-840a-275e8f605524)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/6b482fb2-a685-49e7-a07c-4a9a40dd5fbe)

**Comment by daniel11088** [comment]
Pricing and routings discrepancy applies to fuse and non-fuse

**Comment by Reyzerbit** [comment]
I have this marked as complete, but it is technically ongoing. Additional pricing issues can be put here.
