### ISSUE TITLE
Bug: [Add-on options don't influence price] [Ore3D Version (1.5.2)]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#81]
**Bug:**
When adding an "add-on" option, the total price of the child doesn't change. 

**Recreate:**
1. Load order 40149
2. Click on receipt tab 
3. Scroll down to drainage fitting 
4. update number 
6. Price not change 

**Expected Behavior:**
Total price of child to change by add-on option amount.

**Comment by Reyzerbit** [comment]
Implemented/fixed with version [1.5.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.3)
