### ISSUE TITLE
Bug: "Rock" Option Items Receive Error on ADD

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#818]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/30e76f1e-80b4-4d43-b481-9be94944a3e9)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/9492dcad-a6ee-43c7-9675-8d2d3928d233)

**Comment by Reyzerbit** [comment]
I have been unable to duplicate this issue. If it happens again, please provide me with an EXACT process on how you got to that point.
