### ISSUE TITLE
Bug: Proposal price updating automatically 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#835]
Proposal/sales orders price is updating automatically for predesigned items. This is problematic as it also automatically updates historical records and prices post signed proposal. It also gives no indication that the price has changed as the proposal still shows old pricing date. This should be a manual function that updates the refresh database button is pressed.
S17587
#46683
#45835

**Comment by Reyzerbit** [comment]
This issue is fixed in Ore3D 2.0
