### ISSUE TITLE
Feature: Copy Proposal when Transcribe & Save (in Ore3D 2.0)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#843]
When opening an 'old' proposal in Ore3D 2.0 you'll be presented with 2 options: 

1. transcribe and read only

2. Transcribe and save -- In this instance Ore3D should make a copy of the proposal first - this way if the transcribe fails for some reason we still have the original estimate.

**Comment by Reyzerbit** [comment]
This is already more or less the current behavior in 2.0.

**Comment by Reyzerbit** [comment]
Reopen if im missing something
