### ISSUE TITLE
Bug: Database Update Failed (Sandbox)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#844]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/250df5b6-395a-4a08-8312-ba81a5e2b6c7)

**Comment by MattIsrael** [comment]
Also failed in production release

**Comment by Reyzerbit** [comment]
Duplicate of #809
