### ISSUE TITLE
Bug: Clean Up 'Add Build' options

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#863]
**Can we remove the 'buttons' and make it clickable text/table? we could fit more information on the screen and organize it clearer - I can sketch this up if it's viable.

**Comment by CBarsell** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/e741e16a-c9bd-4767-9d70-ea6869e56df1)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.0.15](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.0.15)
