### ISSUE TITLE
Bug: BOM Hover = Description v2.0.12

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#868]
**Bug:**
there is a lag when hovering over the BOM numbers in a receipts panel.
you have to leave the mouse over it for a few seconds before it shows you the item description.
It would be really cool if it was instantaneous, understandable if there's no work around.

**Comment by Reyzerbit** [comment]
Note to Self: This is a JavaFX limitation i've been interested in. See if setting hover delay programmatically changes better than CSS binding.

**Comment by Reyzerbit** [comment]
JavaFX limitation, hopefully they provide a fix soon
