### ISSUE TITLE
Bug: BOM Search is Buggy

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#869]
**Bug:**
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/af259648-e49d-4313-b491-95fc3384b38d)

- Have Finishes Searchable by item # Like v1

**Comment by Reyzerbit** [comment]
Note to Self: BOM ChoiceBox implementation may need to be written entirely from scratch. Adding too many items to list causes scroll issues on build/non-dev version of Ore3D.

**Comment by Reyzerbit** [comment]
Fixed in [Release 2.0.13](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.0.13)
