### ISSUE TITLE
Allow multi select in product search results

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#871]
Per estimating Team, can we get rid of pictures and add multi select option?

Remove the current selection view. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/4e07521e-9683-4084-bb94-7bb5de6a45bf)

**Comment by Reyzerbit** [comment]
Duplicate of #863
