### ISSUE TITLE
Feature: Add checkbox option to make Misc Charge separate from fuse sections 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#876]
Add checkbox to make misc. charge separate from fuse sections like other options
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/bae70d8a-6bd6-4d0e-96dd-20b90e043122)

**Comment by Reyzerbit** [comment]
This already exists, come talk to me so i can show you wear its hiding 😄
