### ISSUE TITLE
Deleted BOM and Misc Charges not being deleted from description

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#887]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/da1308bb-7f49-420d-8032-b477703ffa1f)

**Comment by Reyzerbit** [comment]
Hey @daniel11088 i am unable to replicate this. If you can get it to happen again, please come show me what you did.
