### ISSUE TITLE
Create Custom Component button gone

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#889]
How do we add a Custom Component?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/da17c401-3d89-4a1d-b709-9b93e8431c73)

**Comment by Reyzerbit** [comment]
Special Order BOM Component button will be getting a complete overhaul so as to work with new Ore3D API.

**Comment by MattIsrael** [comment]
Need ability to override Misc charge qty always associated with child qty. 

This is a workaround for Add Custom Component (already has that functionality).

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.6](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.6)
