### ISSUE TITLE
Feature: Print/Export Proposal with Routings and BOM

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#893]
This would not be a real proposal, but rather a way to export/print Ore3D configurations to facilitate external review. Doesn't need to go through NetSuite in any way. Current preference among estimators and Jake Drake is for a CSV export

If this is viable let me know and I'll flush out the list below for you.

EXAMPLE:
Export Columns(L to R):
- Label
- Description
- Routings
- - CAD (Min; Rate; Margin%; Rate; Price) [same for other routings]
- - Routing Sub-Total

- BOM (Item#; qty; Rate; Cost; Margin; Price) [These would extend right for as many BOM items as there were]

This would facilitate Supply Chain hasty BOM requirements prior to WO creation. Allow estimating to review complex builds away from computer, and other estimating functions that would help us in many review line items.

**Comment by Reyzerbit** [comment]
Marking as planned admin tab feature.

**Comment by Reyzerbit** [comment]
Completed in [Release 2.5.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.5.0)
