### ISSUE TITLE
Back button to take you back to parent

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#926]
Can back button bring you back to the parent instead of main proposal?

**Comment by Reyzerbit** [comment]
Daniel clarified: He means when clicking back button, auto select the parent once top-level is reached

**Comment by Reyzerbit** [comment]
Completed in [2.0.17](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.0.17)

**Comment by daniel11088** [comment]
still not working
