### ISSUE TITLE
Feature Request: Make Tree Disable-able

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#927]
Make Navigation tree disable-able

**Comment by daniel11088** [comment]
Request for expanding menu similar to add build.

Group discussion required.

**Comment by Reyzerbit** [comment]
Completed in [2.0.17](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.0.17)
