### ISSUE TITLE
Searchable Int String Map Spec Issue

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#933]
When selecting the same value as already selected in a searchable dropdown, a different value than selected is returned.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/75223743-e99e-41fd-99f2-77137780ab61)

**Comment by MattIsrael** [comment]
Recommend increasing priority

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.4)
