### ISSUE TITLE
Bug: [Crash on Customer Search] [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#94]
**Bug:**
Ore3D crashed and failed to send it's own bug report.

Creating new proposal.
Project: Ore Test
Customer: [searching for "ore r&d"] - crash

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed/Implemented in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
