### ISSUE TITLE
Feature: Misc Charge Improvements

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#940]
Please add checkbox to misc. charge items so these can be priced separate from parent quantity
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/8e89be4d-7032-48f2-8cf2-2c80e380c465)

Would be nice if there was an optional text box or drop down to add a unit of measure to the qty in a misc charge. 

![image](https://github.com/user-attachments/assets/db5e7dee-1ceb-4902-8adb-46a5d1689241)

Current Description:
-- BUDGETARY PLACEHOLDER: Simple Ipe Bench Slats x 11

Improved Description Example:
-- BUDGETARY PLACEHOLDER: Simple Ipe Bench Slats x 11**LF**
"LF" would be entered in to the misc charge (above).

**Comment by Reyzerbit** [comment]
Completed in [Release 2.4.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.4.0)
