### ISSUE TITLE
API Feature: Allow specific build types to be un-workorder-able

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore-3D-Reports-Changelog#942]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/968f3522-8c8c-48b2-852f-ee09ef08193f)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.0.19](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.0.19)
