### ISSUE TITLE
Bug: New Builds Not Triggering Dirty Listener

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#957]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/f92c40a6-8752-49f0-a087-d1d7da29dd38)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.0)
