### ISSUE TITLE
Bug: Not able to open edit field twice

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#958]
Not able to open the edit popup field again after closing it
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/cecffecd-f434-4788-88c4-be4fccfa5dea)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.0)
