### ISSUE TITLE
Feature: Add option to see entire description field (i.e. Full screen option)

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#959]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/33d39b88-2cf7-48de-9440-b0a1fb2ed911)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.4.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.4.0)
