### ISSUE TITLE
Copied Abstract Builds - Lose the part number on the BOM items 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore-3D-Reports-Changelog#962]
No bommy bom item numbers on the left

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/b2926aa1-c023-4e4e-907f-7d9f2f5ba31d)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.0](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.0)
