### ISSUE TITLE
Feature: 2.0 UI Request

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#963]
Primary objectives:
- Increase information density (remove empty space). 
- Hide/move to bottom redundant or rarely used fields
- increase situational awareness when navigating many lines with children. 

Please engage me once y'all have chewed on this and are ready to discuss further. 

[2.0 UI Request.pdf](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/14781173/2.0.UI.Request.pdf)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.2)
