### ISSUE TITLE
Bug: Open Old Data in New Window Doesn't Show Warning v2.1.1

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#966]
Original Title: Open 1.0 in New Window v2.1.1

If you open a 1.0 in a new window you don't get the big red error indicating this. (We want this error)

Current error when opening 1.0 in NEW WINDOW:
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/77c7377b-43c9-434b-b45c-a3269d8adb1a)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.2)
