### ISSUE TITLE
Bug: Ore3D not unlocking if proposal not saved

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#969]
unknown extent of bug

If you load a proposal, then back out to Home without saving the proposal will NOT be unlocked in NetSuite.

Appears to unlock IF there is a save cycle.

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.2](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.2)
