### ISSUE TITLE
Feature: Improved Recent Order List

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#97]
History of ~20 proposals showing[proposal #] [Project] [Customer]

**Issue:**

**Solution:**

**Alternatives:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed/Implemented in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
