### ISSUE TITLE
Nordic Description Appear when creating WO

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore-3D-Reports-Changelog#975]
<img width="122" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/03247a67-e549-4189-a635-a2d20dc52794">

**Comment by Reyzerbit** [comment]
Completed in [2.1.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.3)
