### ISSUE TITLE
Scrolling on the WO creation screen causes lines to become unselectable. 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore-3D-Reports-Changelog#979]
If you scroll up and down, its randomly makes lines unselectable.

**Comment by Reyzerbit** [comment]
I believe this is associated with #975 , as I cant recreate it after fixing it. I'll keep an eye out in later versions

**Comment by Reyzerbit** [comment]
Completed in [2.1.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.3)
