### ISSUE TITLE
Feature Request: Change Fuse Split UI [1.5.3]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#98]
**Issue:**
Gray box changes to represent scaled length and width of the 'piece'. Depending on dimensions text will appear over the black background and become very difficult to read. 

I don't see any particular value in the 'gray box' changing size (visualization). 

**Solution:**
Recommend displaying this information in a more static table. 

![image](https://user-images.githubusercontent.com/114440644/202490990-4dabb7a2-34cd-432e-be0f-98ec9b67e164.png)

**Comment by Reyzerbit** [comment]
Fixed/Implemented in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
