### ISSUE TITLE
Bug: Reorder causes title change

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#982]
Original Title: Changing FUSE child order changes title of children

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/88ce0673-6e97-429c-9ef4-f0e787c7b5ab)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/ff170fc7-4e77-412a-8d45-d41a7008fa7f)

**Comment by Reyzerbit** [comment]
Completed in [2.1.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.3)
