### ISSUE TITLE
Bug: Conflicts not Updating Properly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#983]
Original Title: Error messages not showing before saving order

I added a 700" fuse child and saved it with out splitting and did not receive an error.

I reopened the order and still no error message was visible but when I added a 1110 the FUSE error message appeared.

**Comment by Reyzerbit** [comment]
Completed in [2.1.3](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.3)
