### ISSUE TITLE
Bug: Fuse Parent BOM and Weights Incorrect [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#99]
**Bug:**
Fuse Planter: 300"x24"x24"H (.125" AL) @ (4) 75" Sections

Appears that items below are not multiplying routings/BOM times the qty before adding to values from other children. 

- Cubic Feet: 50; actually 100
- Weight: does not equal material SF x material weight (1.81lbs/SF for .125")
- Weight also only shows for 2 sections, not 4
- Planted Weight only shows for 2 sections, not 4

**Recreate:**
1. Load order '...'

**Expected Behavior:**

**Additional Context/Questions:**

**Comment by Reyzerbit** [comment]
Fixed in [Update v1.5.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/1.5.4)
