### ISSUE TITLE
Bug: Can generate WO even if Child is disallowed

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore-3D-Reports-Changelog#998]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/b15b4931-8495-4edc-b486-deb70e6871d7)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.4)
