### ISSUE TITLE
Bug: Itemized Messages qty doesn't match # 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#999]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/b0ba966d-b98b-4555-9cd5-255a05a4ba45)

**Comment by Reyzerbit** [comment]
Completed in [Release 2.1.4](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/releases/tag/2.1.4)
